Config.Expressions = {
    { category = "expressions", name = "normal", type = "expression", animation = "pose_normal_1", label = "Normalny" },
    { category = "expressions", name = "angry", type = "expression", animation = "mood_angry_1", label = "Wściekły" },
    { category = "expressions", name = "drunk", type = "expression", animation = "mood_drunk_1", label = "Pijany" },
    { category = "expressions", name = "dumb", type = "expression", animation = "pose_injured_1", label = "Głupi" },
    { category = "expressions", name = "grumpy1", type = "expression", animation = "pose_angry_1", label = "Trochę wściekły" },
    { category = "expressions", name = "grumpy2", type = "expression", animation = "effort_1", label = "Zły" },
    { category = "expressions", name = "grumpy3", type = "expression", animation = "mood_drivefast_1", label = "Naprawdę wściekły" },
    { category = "expressions", name = "happy", type = "expression", animation = "mood_happy_1", label = "Szczęśliwy" },
    { category = "expressions", name = "injured", type = "expression", animation = "mood_injured_1", label = "Ranny" },
    { category = "expressions", name = "aiming", type = "expression", animation = "pose_aiming_1", label = "Celujący" },
    { category = "expressions", name = "shocked", type = "expression", animation = "shocked_1", label = "Zszokowany" },
    { category = "expressions", name = "sleeping", type = "expression", animation = "mood_sleeping_1", label = "Śpiący" },
    { category = "expressions", name = "dead", type = "expression", animation = "dead_1", label = "Martwy" },
    { category = "expressions", name = "smug", type = "expression", animation = "mood_smug_1", label = "Zadowolony z siebie" },
    { category = "expressions", name = "girlgrumpy", type = "expression", animation = "mood_aiming_1", label = "Dziewczyna wściekła" },
    { category = "expressions", name = "stressed", type = "expression", animation = "mood_stressed_1", label = "Stresowany" },
    { category = "expressions", name = "sulking", type = "expression", animation = "mood_sulk_1", label = "Marudny" },
    { category = "expressions", name = "jawpain", type = "expression", animation = "effort_2", label = "Ból szczęki" },
    { category = "expressions", name = "pouty", type = "expression", animation = "effort_3", label = "Dąsający się" },
    { category = "expressions", name = "electrocuted", type = "expression", animation = "electrocuted_1", label = "Porazony prądem" },
    { category = "expressions", name = "joyful", type = "expression", animation = "mood_dancing_low_1", label = "Radosny" },
    { category = "expressions", name = "mouthbreather", type = "expression", animation = "smoking_hold_1", label = "Oddychający ustami" },
}