Config.Walks = {
    { name = "wnormal_male", lib = "move_m@generic", animation = "move_m@generic", flag = 1, label = "Normalny mężczyzna" },
    { name = "wdepressed_male", lib = "move_m@depressed@a", animation = "move_m@depressed@a", flag = 1, label = "Przygnębiony mężczyzna" },
    { name = "wdepressed_female", lib = "move_f@depressed@a", animation = "move_f@depressed@a", flag = 1, label = "Przygnębiona kobieta" },
    { name = "wbusiness", lib = "move_m@business@a", animation = "move_m@business@a", flag = 1, label = "Biznesowy" },
    { name = "wdetermined", lib = "move_m@brave@a", animation = "move_m@brave@a", flag = 1, label = "Zdeterminowany" },
    { name = "wcasual", lib = "move_m@casual@a", animation = "move_m@casual@a", flag = 1, label = "Spokojny i opanowany" },
    { name = "wheavyset", lib = "move_m@fat@a", animation = "move_m@fat@a", flag = 1, label = "Osoba ciężka" },
    { name = "whipster", lib = "move_m@hipster@a", animation = "move_m@hipster@a", flag = 1, label = "Hipster" },
    { name = "wlimping", lib = "move_m@injured", animation = "move_m@injured", flag = 1, label = "Kulejący" },
    { name = "wnervous_fast", lib = "move_m@hurry@a", animation = "move_m@hurry@a", flag = 1, label = "Nerwowy szybki" },
    { name = "whobo", lib = "move_m@hobo@a", animation = "move_m@hobo@a", flag = 1, label = "Bezdomny" },
    { name = "wsad", lib = "move_m@sad@a", animation = "move_m@sad@a", flag = 1, label = "Smutny" },
    { name = "wmuscle", lib = "move_m@muscle@a", animation = "move_m@muscle@a", flag = 1, label = "Umięśniony" },
    { name = "wshocked", lib = "move_m@shocked@a", animation = "move_m@shocked@a", flag = 1, label = "Zszokowany" },
    { name = "wshady", lib = "move_m@shadyped@a", animation = "move_m@shadyped@a", flag = 1, label = "Deviant" },
    { name = "wbuzzed", lib = "move_m@buzzed", animation = "move_m@buzzed", flag = 1, label = "Wyczerpany" },
    { name = "wdetermined_fast", lib = "move_m@hurry_butch@a", animation = "move_m@hurry_butch@a", flag = 1, label = "Zdeterminowany szybki" },
    { name = "whippie", lib = "move_m@money", animation = "move_m@money", flag = 1, label = "Hippie" },
    { name = "wsneaky_run", lib = "move_m@quick", animation = "move_m@quick", flag = 1, label = "Podstępny bieg" },
    { name = "wmaneater", lib = "move_f@maneater", animation = "move_f@maneater", flag = 1, label = "Pożeracz Mężczyzn" },
    { name = "wtwo_bags_and_heels", lib = "move_f@sassy", animation = "move_f@sassy", flag = 1, label = "Dwie torby i szpilki" },
    { name = "warrogant", lib = "move_f@arrogant@a", animation = "move_f@arrogant@a", flag = 1, label = "Arogancki" },
    { name = "wghetto", lib = "move_m@gangster@generic", animation = "move_m@gangster@generic", flag = 1, label = "Gangster" },
    { name = "wslightly_drunk", lib = "move_m@drunk@slightlydrunk", animation = "move_m@drunk@slightlydrunk", flag = 1, label = "Pijany" },
    { name = "wmoderately_drunk", lib = "move_m@drunk@moderatedrunk", animation = "move_m@drunk@moderatedrunk", flag = 1, label = "Bardziej pijany" },
    { name = "wvery_drunk", lib = "move_m@drunk@verydrunk", animation = "move_m@drunk@verydrunk", flag = 1, label = "Najbardziej pijany" },
    { name = "walien_run", lib = "move_m@alien", animation = "move_m@alien", flag = 1, label = "Bieg kosmity" },
    { name = "wballistic", lib = "ANIM_GROUP_MOVE_BALLISTIC", animation = "ANIM_GROUP_MOVE_BALLISTIC", flag = 1, label = "Najcięższy w mieście" },
    { name = "wscared", lib = "ANIM_GROUP_MOVE_LEMAR_ALLEY", animation = "ANIM_GROUP_MOVE_LEMAR_ALLEY", flag = 1, label = "Przestraszony" },
    { name = "wjogger", lib = "move_m@JOG@", animation = "move_m@JOG@", flag = 1, label = "Bieganie" },
    { name = "wgroovy", lib = "ANIM@MOVE_M@GROOVING@", animation = "ANIM@MOVE_M@GROOVING@", flag = 1, label = "Groovy" },
    { name = "wslow_groove", lib = "ANIM@MOVE_M@GROOVING@SLOW@", animation = "ANIM@MOVE_M@GROOVING@SLOW@", flag = 1, label = "Wolny groove" },
    { name = "wflirty", lib = "move_f@chichi", animation = "move_f@chichi", label = "Kurwa" },
    { name = "wfeminine", lib = "move_f@femme@", animation = "move_f@femme@", label = "Kobiecy" },
    { name = "wlimping_heist", lib = "move_heist_lester", animation = "move_heist_lester", label = "Kulejący" },
    { name = "wscared_female", lib = "move_f@scared", animation = "move_f@scared", label = "Przestraszona" },
    { name = "wtough_guy", lib = "move_m@tough_guy@", animation = "move_m@tough_guy@", label = "Twardy facet" },
    { name = "wtough_girl", lib = "move_f@tough_guy@", animation = "move_f@tough_guy@", label = "Twarda dziewczyna" },
    { name = "wslow", lib = "move_characters@jimmy@slow@", animation = "move_characters@jimmy@slow@", label = "Wolny" },
    { name = "wangry", lib = "clipset@move@trash_fast_turn", animation = "clipset@move@trash_fast_turn", label = "ZŁY" },
    { name = "wsassy", lib = "move_m@sassy", animation = "move_m@sassy", label = "Zuchwały" },
    { name = "wproud_ghetto", lib = "move_m@gangster@ng", animation = "move_m@gangster@ng", label = "Dumny gangster" },
    { name = "wtired_ghetto", lib = "move_m@gangster@var_e", animation = "move_m@gangster@var_e", label = "Zmęczony gangster" },
    { name = "wsad_ghetto", lib = "move_m@gangster@var_f", animation = "move_m@gangster@var_f", label = "Smutny gangster" },
    { name = "wstressed_ghetto", lib = "move_m@gangster@var_i", animation = "move_m@gangster@var_i", label = "Stresowany gangster" },
    { name = "wfranklin", lib = "move_p_m_one", animation = "move_p_m_one", label = "Franklin" },
    { name = "wflee", lib = "move_f@flee@a", animation = "move_f@flee@a", label = "Uciekaj o życie" },
    { name = "wpiggy", lib = "move_characters@franklin@fire", animation = "move_characters@franklin@fire", label = "Gruby jak świnia" },
    { name = "wtough_retard", lib = "move_characters@michael@fire", animation = "move_characters@michael@fire", label = "Twardy debil" },
    { name = "wtough", lib = "move_m@bag", animation = "move_m@bag", label = "Twardy" },
    { name = "wspank", lib = "move_f@heels@c", animation = "move_f@heels@c", flag = 1, label = "Ściśnij tyłek" },
    { name = "whurry", lib = "move_f@hurry@a", animation = "move_f@hurry@a", flag = 1, label = "Pośpiesz się" },
    { name = "wdefault", lib = "", animations = {}, label = "Normalny styl chodzenia" },
    { name = "wcasual2", lib = "move_m@casual@b", animation = "move_m@casual@b", flag = 1, label = "Swobodny 2" },
    { name = "wcasual3", lib = "move_m@casual@c", animation = "move_m@casual@c", flag = 1, label = "Swobodny 3" },
    { name = "wcasual4", lib = "move_m@casual@d", animation = "move_m@casual@d", flag = 1, label = "Swobodny 4" },
    { name = "wcasual5", lib = "move_m@casual@e", animation = "move_m@casual@e", flag = 1, label = "Swobodny 5" },
    { name = "wcasual6", lib = "move_m@casual@f", animation = "move_m@casual@f", flag = 1, label = "Swobodny 6" },
    { name = "wconfident", lib = "move_m@confident", animation = "move_m@confident", flag = 1, label = "Pewny siebie" },
    { name = "wbusiness2", lib = "move_m@business@b", animation = "move_m@business@b", flag = 1, label = "Biznesowy 2" },
    { name = "wbusiness3", lib = "move_m@business@c", animation = "move_m@business@c", flag = 1, label = "Biznesowy 3" },
    { name = "wheels2", lib = "move_f@heels@d", animation = "move_f@heels@d", flag = 1, label = "Szpilki 2" },
    { name = "wposh", lib = "move_m@posh@", animation = "move_m@posh@", flag = 1, label = "Elegancki" },
    { name = "wswagger", lib = "move_m@swagger", animation = "move_m@swagger", flag = 1, label = "Swagger" },
    { name = "wchubby", lib = "move_chubby", animation = "move_chubby", flag = 1, label = "Pulchny" },
    { name = "wwidester", lib = "move_m@fire", animation = "move_m@fire", flag = 1, label = "Widester" },
    { name = "wjanitor", lib = "move_p_m_zero_janitor", animation = "move_p_m_zero_janitor", flag = 1, label = "Woźny" },
    { name = "wjanitorslow", lib = "move_p_m_zero_slow", animation = "move_p_m_zero_slow", flag = 1, label = "Woźny Wolny" },
    { name = "wmichael", lib = "move_ped_bucket", animation = "move_ped_bucket", flag = 1, label = "Michael" },
    { name = "wtrevor", lib = "move_p_m_two", animation = "move_p_m_two", flag = 1, label = "Trevor" },
}