Config = {}

-- Wyłączone do czasu startu serwera!!!
-- Config.EventsRateLimits = {
--     {event = "esx:setJob", limit =	3, timer = 3},
--     {event = "qb-smallresources:server:additem", limit =	3, timer = 3},
--     {event = "player:receiveitem", limit =	3, timer = 3},
--     {event = "esx_ambulancejob:setdeathstatus", limit =	3, timer = 3},
--     {event = "zv_elektromonteur:paymoney", limit =	3, timer = 3},
--     {event = "inside-gardener:payoutnow", limit =	3, timer = 3},
--     {event = "cfx-hu-ems:heal", limit =	3, timer = 3},
--     {event = "fuel:pay", limit =	3, timer = 3},
--     {event = "bounty:giveitem", limit =	3, timer = 3},
--     {event = "utk_oh:rewardcash", limit =	3, timer = 3},
--     {event = "casino:tradeinchips", limit =	3, timer = 3},
--     {event = "esx_ambulancejob:revive", limit =	3, timer = 3},
--     {event = "esx-qalle-jail:prisonworkreward", limit =	3, timer = 3},
--     {event = "ox_inventory:giveitem", limit =	3, timer = 3},
--     {event = "esx_billing:sendbill", limit =	3, timer = 3},
--     {event = "xfsd-listing:getnewjob", limit =	3, timer = 3},
--     {event = "esx_yacht:reward", limit =	3, timer = 3},
--     {event = "esx_marvin_stable_lateral_position:medic", limit =	3, timer = 3},
--     {event = "okokbanking:depositmoney", limit =	3, timer = 3},
--     {event = "tfoadakgt9vdu", limit =3, timer = 3},
--     {event = "esx_vangelico_robbery:gioielli", limit =	3, timer = 3},
--     {event = "postal_job:end", limit =	3, timer = 3},
--     {event = "mkbuss:givereward", limit =	3, timer = 3},
--     {event = "fp-jobs:rewardfisher", limit =	3}, timer = 3,
--     {event = "esx_advancedgarage:payhealth", limit =	3, timer = 3},
--     {event = "esx:spawnvehicle", limit =	3, timer = 3},
--     {event = "esx_core:getNewMessage", limit =	6, timer = 3},
--     {event = "qf_banking:getPIN", limit =	6, timer = 3},
--     {event = "qf-banking:getAccounts", limit =	6, timer = 3},
--     {event = "exotic_houses:joinQueue", limit =	6, timer = 3},
--     {event = "exotic_houses:removeQueue", limit =	6, timer = 3},
--     {event = "exotic_gruppesechs:joinQueue", limit =	6, timer = 3},
--     {event = "exotic_gruppesechs:removeQueue", limit =	6, timer = 3},
--     {event = "exotic_tracker:removeQueue", limit =	6, timer = 3},
--     {event = "exotic_tracker:joinQueue", limit =	6, timer = 3},
--     {event = "exotic_flare:removeQueue", limit =	6, timer = 3},
--     {event = "exotic_flare_ls:removeQueue", limit =	6, timer = 3},
--     {event = "exotic_flare:joinQueue", limit =	6, timer = 3},
--     {event = "exotic_flare_ls:joinQueue", limit =	6, timer = 3},
--     {event = "esx_core_narcosell:onPayForDrugs", limit = 6, timer = 3},
--     {event = "esx_drugs:onCollectingDrugs", limit =	6, timer = 3},
--     {event = "esx_drugs:onProcessDrugs", limit =	6, timer = 3},
--     {event = "exotic_rybak:onTransferThing", limit =	6, timer = 3},
--     {event = "exotic_rybak:onCollectThing", limit =	6, timer = 3},
--     {event = "exotic_drops:takingDrop", limit = 6, timer = 3},
-- 	{event = "exotic_drops:getDrop", limit =	3, timer = 3},
-- 	{event = "esx_core:lombardShop", limit = 6, timer = 3},
-- 	{event = "esx_core:lombardShopSecond", limit = 6, timer = 3},
-- 	{event = "esx_core:lombardShopThird", limit = 6, timer = 3},
-- 	{event = "esx_core:lombardShopFourth", limit = 6, timer = 3},
-- 	{event = "esx_core:useAtBusiness", limit = 6, timer = 3},
-- 	{event = "esx_core_robnpc:giveReward", limit = 6, timer = 3},
-- 	{event = "exotic_houses:takeItems", limit = 6, timer = 3},
-- 	{event = 'esx_mechanik:onNPCJobMissionCompleted', limit = 6, timer = 3},
-- 	{event = 'esx_laundry:tryToWash', limit = 6, timer = 3},
-- 	{event = 'exotic_bosshub:getReward', limit = 6, timer = 3},
-- 	{event = 'exotic_bosshub:dm_buyItem', limit = 6, timer = 3},
-- 	{event = 'exotic_tracker:onReward', limit = 6, timer = 3 },
-- 	{event = 'exotic_gruppesechs:robDone', limit = 6, timer = 3},
-- 	{event = 'exotic_flare:success', limit = 6, timer = 3},
-- 	{event = 'exotic_cashregister:getItems', limit = 6, timer = 3},
-- 	{event = 'esx_identity:Items', limit = 6, timer = 3},
-- 	{event = 'esx_identity:finishRegisteringPlayer', limit = 6, timer = 3},
-- 	{event = 'esx_core_contract:buyContract', limit = 6, timer = 3},
-- }

Config.ClientEventsBlacklist = {
	'HCheat:TempDisableDetection',
	'BsCuff:Cuff696999',
	'adminmenu:allowall',
	'antilynx8r4a:anticheat',
	'antilynxr4:detect',
	'ynx8:anticheat',
	'lynx8:anticheat',
	'hentailover:xdlol',
	'antilynx8:anticheat',
	'antilynxr6:detection',
	'FAC:EzExec',
	'h:xd',
	'redst0nia:checking',
	'oxmysql:request',
	'InteractSound_SV:PlayOnAll',
	'esx_policejob:requestarrest',
	'gangrp_mechanics:createLockpick',
}

Config.ServerEventsBlacklist = {
	'HCheat:TempDisableDetection',
	'BsCuff:Cuff696999',
	'adminmenu:allowall',
	'antilynx8r4a:anticheat',
	'antilynxr4:detect',
	'ynx8:anticheat',
	'lynx8:anticheat',
	'hentailover:xdlol',
	'antilynx8:anticheat',
	'antilynxr6:detection',
	'FAC:EzExec',
	'h:xd',
	'redst0nia:checking',
	'oxmysql:request',
	'InteractSound_SV:PlayOnAll',
	'esx_policejob:requestarrest',
	'gangrp_mechanics:createLockpick',
}

Config.WeaponsBlacklist = {
	[GetHashKey('weapon_marksmanpistol')] = 'weapon_marksmanpistol',
	[GetHashKey('weapon_revolver')] = 'weapon_revolver',
	[GetHashKey('weapon_revolver_mk2')] = 'weapon_revolver_mk2',
	[GetHashKey('weapon_raypistol')] = 'weapon_raypistol',
	[GetHashKey('weapon_gadgetpistol')] = 'weapon_gadgetpistol',
	[GetHashKey('weapon_raycarbine')] = 'weapon_raycarbine',
	[GetHashKey('weapon_tecpistol')] = 'weapon_tecpistol',
	[GetHashKey('weapon_assaultshotgun')] = 'weapon_assaultshotgun',
	[GetHashKey('weapon_bullpupshotgun')] = 'weapon_bullpupshotgun',
	[GetHashKey('weapon_musket')] = 'weapon_musket',
	[GetHashKey('weapon_heavyshotgun')] = 'weapon_heavyshotgun',
	[GetHashKey('weapon_dbshotgun')] = 'weapon_dbshotgun',
	[GetHashKey('weapon_autoshotgun')] = 'weapon_autoshotgun',
	[GetHashKey('weapon_combatshotgun')] = 'weapon_combatshotgun',
	[GetHashKey('eapon_militaryrifle')] = 'eapon_militaryrifle',
	[GetHashKey('weapon_tacticalrifle')] = 'weapon_tacticalrifle',
	[GetHashKey('weapon_heavyrifle')] = 'weapon_heavyrifle',
	[GetHashKey('weapon_mg')] = 'weapon_mg',
	[GetHashKey('weapon_combatmg')] = 'weapon_combatmg',
	[GetHashKey('weapon_combatmg_mk2')] = 'weapon_combatmg_mk2',
	[GetHashKey('weapon_gusenberg')] = 'weapon_gusenberg',
	[GetHashKey('weapon_sniperrifle')] = 'weapon_sniperrifle',
	[GetHashKey('weapon_heavysniper')] = 'weapon_heavysniper',
	[GetHashKey('weapon_heavysniper_mk2')] = 'weapon_heavysniper_mk2',
	[GetHashKey('weapon_marksmanrifle')] = 'weapon_marksmanrifle',
	[GetHashKey('weapon_marksmanrifle_mk2')] = 'weapon_marksmanrifle_mk2',
	[GetHashKey('weapon_precisionrifle')] = 'weapon_precisionrifle',
	[GetHashKey('weapon_rpg')] = 'weapon_rpg',
	[GetHashKey('weapon_grenadelauncher')] = 'weapon_grenadelauncher',
	[GetHashKey('weapon_grenadelauncher_smoke')] = 'weapon_grenadelauncher_smoke',
	[GetHashKey('weapon_minigun')] = 'weapon_minigun',
	[GetHashKey('weapon_firework')] = 'weapon_firework',
	[GetHashKey('weapon_railgun')] = 'weapon_railgun',
	[GetHashKey('weapon_hominglauncher')] = 'weapon_hominglauncher',
	[GetHashKey('weapon_compactlauncher')] = 'weapon_compactlauncher',
	[GetHashKey('weapon_rayminigun')] = 'weapon_rayminigun',
	[GetHashKey('weapon_emplauncher')] = 'weapon_emplauncher',
	[GetHashKey('weapon_railgunxm3')] = 'weapon_railgunxm3',
	[GetHashKey('weapon_grenade')] = 'weapon_grenade',
	[GetHashKey('weapon_proxmine')] = 'weapon_proxmine',
	[GetHashKey('weapon_pipebomb')] = 'weapon_pipebomb',
	[GetHashKey('weapon_acidpackage')] = 'weapon_acidpackage',
}

Config.WhitelistedCarResources = {
	["monitor"] = true,
	["es_extended"] = true,
	['esx_ambulance'] = true,
	['esx_dmvschool'] = true,
	['esx_gym'] = true,
	['esx_jobs'] = true,
	['esx_mechanik'] = true,
	['esx_police'] = true,
	['esx_carmarket'] = true,
    ['esx_core'] = true,
    ['esx_hud'] = true,
	['esx_prisons'] = true,
	['esx_tracker'] = true,
	['exotic_businesses'] = true,
	['exotic_rentalsystem'] = true,
	['exotic_flyrent'] = true,
	['exotic_taxijob'] = true,
	['exotic_coinranking'] = true,
	['ox_inventory'] = true,
    ['qf-mdt'] = true,
    ['qf-mdt-ems'] = true,
    ['qf-mdt-lsc'] = true,
	['qf-mdt-ec'] = true,
	['op-garages'] = true,
	['op-crime'] = true,
	['op-multicharacter'] = true,
	["17mov_GarbageCollector"] = true,
	["17mov_Postman"] = true,
	['uz_Dealerships'] = true,
	["jg-mechanic"] = true,
	['p_dojjob'] = true,
    ['lb-phone'] = true,
	['lb-phoneprop'] = true,
	['spawnmanager'] = true
}

-- Wyłączone do czasu startu serwera!!
-- Config.WhitelistedPropsResources = {
-- 	["monitor"] = true,
-- 	["es_extended"] = true,
-- 	["i_tuningmenu"] = true,
-- 	["i_shrooms"] = true,
--     ['lb-phone'] = true,
-- 	['lb-phoneprop'] = true,
-- 	['qs-housing'] = true,
-- 	['op-garages'] = true,
-- 	['s1n_lib'] = true,
-- 	['esx_ambulance'] = true,
-- 	['esx_carmarket'] = true,
--     ['esx_core'] = true,
-- 	['esx_gym'] = true,
-- 	['esx_jobs'] = true,
-- 	['esx_mechanik'] = true,
-- 	['esx_police'] = true,
-- 	['esx_selldrugs'] = true,
-- 	['esx_tracker'] = true,
-- 	['esx_vehicleshop'] = true,
-- 	["17mov_GarbageCollector"] = true,
-- 	["17mov_Postman"] = true,
-- 	['ox_inventory'] = true,
-- 	['bablo-animations'] = true,
--     ['qf-mdt'] = true,
--     ['qf-mdt-ems'] = true,
--     ['qf-mdt-lsc'] = true,
-- 	['qf-mdt-doj'] = true,
--     ['esx_society'] = true,
--     ['esx_hud'] = true,
-- 	['esx_orgs'] = true,
--     ['esx_basicneeds'] = true,
--     ['JustBilliard'] = true,
--     ['xradio'] = true,
-- 	['esx_drops'] = true,
-- 	['esx_dmvschool'] = true,
-- }

-- Wyłączone do czasu startu serwera!!
-- Config.WhitelistedPedResources = {
--     ["rcore_casino"] = true,
--     ["esx_core"] = true,
--     ["exotic_gruppesechs"] = true,
-- 	['esx_laundry'] = true,
-- 	['hs_bans'] = true,
-- 	['hs_houserobbery'] = true,
-- 	['exotic_holdup'] = true,
-- }

Config.CarsBL = {
	[GetHashKey('dinghy5')] = 'dinghy5',
	[GetHashKey('longfin')] = 'longfin',
	[GetHashKey('kosatka')] = 'kosatka',
	[GetHashKey('patrolboat')] = 'patrolboat',
	[GetHashKey('cerberus')] = 'cerberus',
	[GetHashKey('cerberus2')] = 'cerberus2',
	[GetHashKey('cerberus3')] = 'cerberus3',
	[GetHashKey('hauler2')] = 'hauler2',
	[GetHashKey('phantom2')] = 'phantom2',
	[GetHashKey('terbyte')] = 'terbyte',
	[GetHashKey('issi3')] = 'issi3',
	[GetHashKey('issi4')] = 'issi4',
	[GetHashKey('issi5')] = 'issi5',
	[GetHashKey('issi6')] = 'issi6',
	[GetHashKey('ambulance')] = 'ambulance',
	[GetHashKey('fbi')] = 'fbi',
	[GetHashKey('fbi2')] = 'fbi2',
	[GetHashKey('firetruk')] = 'firetruk',
	[GetHashKey('lguard')] = 'lguard',
	[GetHashKey('police')] = 'police',
	[GetHashKey('police2')] = 'police2',
	[GetHashKey('police3')] = 'police3',
	[GetHashKey('police4')] = 'police4',
	[GetHashKey('policeb')] = 'policeb',
	[GetHashKey('policeold1')] = 'policeold1',
	[GetHashKey('policeold2')] = 'policeold2',
	[GetHashKey('pranger')] = 'pranger',
	[GetHashKey('riot2')] = 'riot2',
	[GetHashKey('sheriff')] = 'sheriff',
	[GetHashKey('metrotrain')] = 'metrotrain',
	[GetHashKey('freightcont2')] = 'freightcont2',
	[GetHashKey('freightgrain')] = 'freightgrain',
	[GetHashKey('tankercar')] = 'tankercar',
	[GetHashKey('freightcar2')] = 'freightcar2',
	[GetHashKey('freightcar')] = 'freightcar',
	[GetHashKey('freightcont1')] = 'freightcont1',
	[GetHashKey('freight2')] = 'freight2',
	[GetHashKey('sheriff2')] = 'sheriff2',
	[GetHashKey('akula')] = 'akula',
	[GetHashKey('annihilator')] = 'annihilator',
	[GetHashKey('buzzard')] = 'buzzard',
	[GetHashKey('cargobob')] = 'cargobob',
	[GetHashKey('cargobob2')] = 'cargobob2',
	[GetHashKey('cargobob3')] = 'cargobob3',
	[GetHashKey('cargobob4')] = 'cargobob4',
	[GetHashKey('hunter')] = 'hunter',
	[GetHashKey('savage')] = 'savage',
	[GetHashKey('skylift')] = 'skylift',
	[GetHashKey('valkyrie')] = 'valkyrie',
	[GetHashKey('valkyrie2')] = 'valkyrie2',
	[GetHashKey('annihilator2')] = 'annihilator2',
	[GetHashKey('bulldozer')] = 'bulldozer',
	[GetHashKey('cutter')] = 'cutter',
	[GetHashKey('dump')] = 'dump',
	[GetHashKey('handler')] = 'handler',
	[GetHashKey('apc')] = 'apc',
	[GetHashKey('barracks')] = 'barracks',
	[GetHashKey('barracks2')] = 'barracks2',
	[GetHashKey('barracks3')] = 'barracks3',
	[GetHashKey('barrage')] = 'barrage',
	[GetHashKey('chernobog')] = 'chernobog',
	[GetHashKey('crusader')] = 'crusader',
	[GetHashKey('halftrack')] = 'halftrack',
	[GetHashKey('khanjali')] = 'khanjali',
	[GetHashKey('minitank')] = 'minitank',
	[GetHashKey('rhino')] = 'rhino',
	[GetHashKey('scarab')] = 'scarab',
	[GetHashKey('scarab2')] = 'scarab2',
	[GetHashKey('scarab3')] = 'scarab3',
	[GetHashKey('thruster')] = 'thruster',
	[GetHashKey('trailersmall2')] = 'trailersmall2',
	[GetHashKey('vetir')] = 'vetir',
	[GetHashKey('oppressor')] = 'oppressor',
	[GetHashKey('oppressor2')] = 'oppressor2',
	[GetHashKey('dukes2')] = 'dukes2',
	[GetHashKey('dominator6')] = 'dominator6',
	[GetHashKey('blazer5')] = 'blazer5',
	[GetHashKey('bruiser')] = 'bruiser',
	[GetHashKey('bruiser2')] = 'bruiser2',
	[GetHashKey('bruiser3')] = 'bruiser3',
	[GetHashKey('brutus')] = 'brutus',
	[GetHashKey('brutus2')] = 'brutus2',
	[GetHashKey('caracara')] = 'caracara',
	[GetHashKey('dune2')] = 'dune2',
	[GetHashKey('dune3')] = 'dune3',
	[GetHashKey('dune4')] = 'dune4',
	[GetHashKey('dune5')] = 'dune5',
	[GetHashKey('insurgent')] = 'insurgent',
	[GetHashKey('insurgent2')] = 'insurgent2',
	[GetHashKey('insurgent3')] = 'insurgent3',
	[GetHashKey('menacer')] = 'menacer',
	[GetHashKey('nightshark')] = 'nightshark',
	[GetHashKey('technical')] = 'technical',
	[GetHashKey('technical2')] = 'technical2',
	[GetHashKey('technical3')] = 'technical3',
	[GetHashKey('alphaz1')] = 'alphaz1',
	[GetHashKey('avenger')] = 'avenger',
	[GetHashKey('avenger2')] = 'avenger2',
	[GetHashKey('besra')] = 'besra',
	[GetHashKey('bombushka')] = 'bombushka',
	[GetHashKey('cargoplane')] = 'cargoplane',
	[GetHashKey('cargoplane2')] = 'cargoplane2',
	[GetHashKey('cuban800')] = 'cuban800',
	[GetHashKey('hydra')] = 'hydra',
	[GetHashKey('lazer')] = 'lazer',
	[GetHashKey('molotok')] = 'molotok',
	[GetHashKey('pyro')] = 'pyro',
	[GetHashKey('rogue')] = 'rogue',
	[GetHashKey('starling')] = 'starling',
	[GetHashKey('strikeforce')] = 'strikeforce',
	[GetHashKey('titan')] = 'titan',
	[GetHashKey('tula')] = 'tula',
	[GetHashKey('volatol')] = 'volatol',
	[GetHashKey('alkonost')] = 'alkonost',
	[GetHashKey('baller5')] = 'baller5',
	[GetHashKey('baller6')] = 'baller6',
	[GetHashKey('xls2')] = 'xls2',
	[GetHashKey('squaddie')] = 'squaddie',
	[GetHashKey('cog552')] = 'cog552',
	[GetHashKey('cognoscenti2')] = 'cognoscenti2',
	[GetHashKey('limo2')] = 'limo2',
	[GetHashKey('brickade')] = 'brickade',
	[GetHashKey('pbus2')] = 'pbus2',
	[GetHashKey('rallytruck')] = 'rallytruck',
	[GetHashKey('wastelander')] = 'wastelander',
	[GetHashKey('kuruma2')] = 'kuruma2',
	[GetHashKey('schafter6')] = 'schafter6',
	[GetHashKey('zr3803')] = 'zr3803',
	[GetHashKey('zr380')] = 'zr380',
	[GetHashKey('zr3802')] = 'zr3802',
	[GetHashKey('shamal')] = 'shamal',
	[GetHashKey('nimbus')] = 'nimbus',
	[GetHashKey('velum')] = 'velum',
	[GetHashKey('luxor')] = 'luxor',
	[GetHashKey('stunt')] = 'stunt',
	[GetHashKey('mammatus')] = 'mammatus',
	[GetHashKey('vestra')] = 'vestra',
	[GetHashKey('blimp2')] = 'blimp2',
	[GetHashKey('blimp')] = 'blimp',
	[GetHashKey('deluxo')] = 'deluxo'
}

Config.ExplosionBlacklist = {
	[1] = true,
	[4] = true,
	[5] = true,
	[25] = true,
	[32] = true,
	[33] = true,
	[36] = true,
	[37] = true,
	[70] = true
}