Config = {}

Config.DriveBySpeedLimit = 60 -- Limit prędkości dla DB (km/h)

Config.Recoils = {
	[`WEAPON_STUNGUN`] = { 0.1, 1.1, 0.02, 0.03 },      -- STUN GUN
	[`WEAPON_SNSPISTOL`] = { 3.5, 4.5, 0.02, 0.03 },    -- SNS PISTOL
	[`WEAPON_SNSPISTOL_MK2`] = { 2.5, 3.0, 0.02, 0.03 }, -- SNS PISTOL MK2
	[`WEAPON_VINTAGEPISTOL`] = { 2.5, 3.0, 0.02, 0.03 }, -- VINTAGE PISTOL
	[`WEAPON_PISTOL`] = { 2.5, 3.0, 0.02, 0.03 },       -- PISTOL
	[`WEAPON_PISTOL_MK2`] = { 2.5, 3.0, 0.02, 0.03 },   -- PISTOL MK2
	[`WEAPON_COMBATPISTOL`] = { 2.5, 3.0, 100.0, 100.0 }, -- COMBAT PISTOL
	[`WEAPON_CERAMICPISTOL`] = { 2.5, 3.0, 0.02, 0.03 }, -- CERAMIC PISTOL
	[`WEAPON_PISTOLXM3`] = { 1.5, 2.0, 0.02, 0.03 },    -- PISTOL XM3
	[`WEAPON_HEAVYPISTOL`] = { 1.5, 2.0, 0.02, 0.03 },  -- HEAVY PISTOL
	[`WEAPON_MICROSMG`] = { 0.15, 0.50, 0.02, 0.03 },   -- MICRO SMG (UZI)
	[`WEAPON_SMG`] = { 0.15, 0.50, 0.02, 0.03 },        -- SMG
	[`WEAPON_COMBATPDW`] = { 0.15, 0.50, 0.02, 0.03 },  -- COMBAT PDW
	[`WEAPON_ASSAULTRIFLE`] = { 0.10, 0.40, 0.02, 0.03 }, -- ASSAULT RIFLE
	[`WEAPON_CARBINERIFLE`] = { 0.10, 0.40, 0.02, 0.03 }, -- CARBINE RIFLE
	[`WEAPON_MILITARYRIFLE`] = { 0.10, 0.40, 0.02, 0.03 }, -- MILITARY RIFLE
}

Config.Effects = {
	[`WEAPON_STUNGUN`] = { 0.01, 0.02, 0.02, 0.03 },    -- STUN GUN
	[`WEAPON_SNSPISTOL`] = { 0.13, 0.20, 0.02, 0.03 },  -- SNS PISTOL
	[`WEAPON_SNSPISTOL_MK2`] = { 0.07, 0.13, 0.02, 0.03 }, -- SNS PISTOL MK2
	[`WEAPON_VINTAGEPISTOL`] = { 0.07, 0.13, 0.02, 0.03 }, -- VINTAGE PISTOL
	[`WEAPON_PISTOL`] = { 0.07, 0.13, 0.02, 0.03 },     -- PISTOL
	[`WEAPON_PISTOL_MK2`] = { 0.07, 0.13, 0.02, 0.03 }, -- PISTOL MK2
	[`WEAPON_COMBATPISTOL`] = { 0.07, 0.13, 0.02, 0.03 }, -- COMBAT PISTOL
	[`WEAPON_CERAMICPISTOL`] = { 0.07, 0.13, 0.02, 0.03 }, -- CERAMIC PISTOL
	[`WEAPON_PISTOLXM3`] = { 0.05, 0.10, 0.02, 0.03 },  -- PISTOL XM3
	[`WEAPON_HEAVYPISTOL`] = { 0.05, 0.10, 0.16, 0.16 }, -- HEAVY PISTOL
	[`WEAPON_PISTOL50`] = { 0.05, 0.10, 0.4, 0.4 },     -- PISTOL .50
	[`WEAPON_APPISTOL`] = { 0.05, 0.10, 0.07, 0.07 },   -- PPANC
	[`WEAPON_MACHINEPISTOL`] = { 0.05, 0.10, 0.07, 0.07 }, -- MACHINEPISTOL
	[`WEAPON_MICROSMG`] = { 0.04, 0.08, 0.1, 0.1 },     -- MICRO SMG (UZI)
	[`WEAPON_SMG`] = { 0.04, 0.08, 0.08, 0.08 },        -- SMG
	[`WEAPON_SMG_MK2`] = { 0.04, 0.08, 0.13, 0.13 },    -- SMG MK2
	[`WEAPON_MINISMG`] = { 0.04, 0.08, 0.1, 0.1 },      -- MINI SMG
	[`WEAPON_COMBATPDW`] = { 0.04, 0.08, 0.04, 0.04 },  -- COMBAT PDW
	[`WEAPON_ASSAULTRIFLE`] = { 0.02, 0.04, 0.1, 0.1 }, -- ASSAULT RIFLE
	[`WEAPON_CARBINERIFLE`] = { 0.02, 0.04, 0.1, 0.1 }, -- CARBINE RIFLE
	[`WEAPON_MILITARYRIFLE`] = { 0.02, 0.04, 0.07, 0.07 }, -- MILITARY RIFLE
	[`WEAPON_COMPACTRIFLE`] = { 0.02, 0.04, 0.12, 0.12 }, -- COMPACT RIFLE
	[`WEAPON_MUSKET`] = { 0.02, 0.04, 3.0, 3.0 },       -- MUSKET
}

Config.Visuals = {
	["trafficLight.near.intensity"] = 0.3,
	["trafficLight.near.radius"] = 5.0,
	["trafficLight.near.outerConeAngle"] = 25.0,
	["trafficLight.near.coronaHDR"] = 1.5,
	["trafficLight.near.coronaSize"] = 0.3,
	["trafficLight.farFadeStart"] = 180.0,
	["trafficLight.farFadeEnd"] = 230.0,
	["trafficLight.nearFadeStart"] = 90.0,
	["trafficLight.nearFadeEnd"] = 120.0,
	["car.sirens.ShadowFade"] = 45.0,
	["car.sirens.intensity"] = 60.0,
	["car.sirens.radius"] = 35.0,
	["Tonemapping.dark.filmic.A"] = 0.4,
	["Tonemapping.dark.filmic.B"] = 0.27,
	["Tonemapping.dark.filmic.C"] = 0.25,
	["lodlight.corona.size"] = 1.5,
	["misc.coronas.sizeScaleGlobal"] = 1.0,
	["misc.coronas.intensityScaleGlobal"] = 0.2,
	["misc.coronas.intensityScaleWater"] = 0.0,
	["misc.coronas.sizeScaleWater"] = 0.0,
	["misc.coronas.screenspaceExpansionWater"] = 0.0,
	["misc.coronas.zBiasMultiplier"] = 15.0,
	["misc.coronas.zBias.fromFinalSizeMultiplier"] = 0.05,
	["misc.coronas.underwaterFadeDist"] = 1.5,
	["misc.coronas.screenEdgeMinDistForFade"] = 0.0,
}

Config.VehicleDamage = {
	deformationMultiplier = -1,      -- How much should the vehicle visually deform from a collision. Range 0.0 to 10.0 Where 0.0 is no deformation and 10.0 is 10 sztuk deformation. -1 = Don't touch. Visual damage does not sync well to other players.
	deformationExponent = 0.05,      -- How much should the handling file deformation setting be compressed toward 1.0. (Make cars more similar). A value of 1=no change. Lower values will compress more, values above 1 it will expand. Dont set to zero or negative.
	collisionDamageExponent = 0.05,  -- How much should the handling file deformation setting be compressed toward 1.0. (Make cars more similar). A value of 1=no change. Lower values will compress more, values above 1 it will expand. Dont set to zero or negative.

	damageFactorEngine = 3.0,        -- Sane values are 1 to 100. Higher values means more damage to vehicle. A good starting point is 10
	damageFactorBody = 3.0,          -- Sane values are 1 to 100. Higher values means more damage to vehicle. A good starting point is 10
	damageFactorPetrolTank = 32.0,   -- Sane values are 1 to 200. Higher values means more damage to vehicle. A good starting point is 64
	engineDamageExponent = 1.0,      -- How much should the handling file engine damage setting be compressed toward 1.0. (Make cars more similar). A value of 1=no change. Lower values will compress more, values above 1 it will expand. Dont set to zero or negative.
	weaponsDamageMultiplier = 0.01,  -- How much damage should the vehicle get from weapons fire. Range 0.0 to 10.0, where 0.0 is no damage and 10.0 is 10 sztuk damage. -1 = don't touch
	degradingHealthSpeedFactor = 8,  -- Speed of slowly degrading health, but not failure. Value of 10 means that it will take about 0.25 second per health point, so degradation from 800 to 305 will take about 2 minutes of clean driving. Higher values means faster degradation
	cascadingFailureSpeedFactor = 8.0, -- Sane values are 1 to 100. When vehicle health drops below a certain point, cascading failure sets in, and the health drops rapidly until the vehicle dies. Higher values means faster failure. A good starting point is 8

	degradingFailureThreshold = 200.0, -- Below this value, slow health degradation will set in
	cascadingFailureThreshold = 180.0, -- Below this value, health cascading failure will set in
	engineSafeGuard = 100.0,         -- Final failure value. Set it too high, and the vehicle won't smoke when disabled. Set too low, and the car will catch fire from a single bullet to the engine. At health 100 a typical car can take 3-4 bullets to the engine before catching fire.

	torqueMultiplierEnabled = true,  -- Decrease engine torque as engine gets more and more damaged

	limpMode = false,                -- If true, the engine never fails completely, so you will always be able to get to a mechanic unless you flip your vehicle and preventVehicleFlip is set to true
	limpModeMultiplier = 0.05,       -- The torque multiplier to use when vehicle is limping. Sane values are 0.05 to 0.25

	preventVehicleFlip = true,       -- If true, you can't turn over an upside down vehicle

	sundayDriver = false,            -- If true, the accelerator response is scaled to enable easy slow driving. Will not prevent full throttle. Does not work with binary accelerators like a keyboard. Set to false to disable. The included stop-without-reversing and brake-light-hold feature does also work for keyboards.
	sundayDriverAcceleratorCurve = 7.5, -- The response curve to apply to the accelerator. Range 0.0 to 10.0. Higher values enables easier slow driving, meaning more pressure on the throttle is required to accelerate forward. Does nothing for keyboard drivers
	sundayDriverBrakeCurve = 5.0,    -- The response curve to apply to the Brake. Range 0.0 to 10.0. Higher values enables easier braking, meaning more pressure on the throttle is required to brake hard. Does nothing for keyboard drivers

	displayBlips = false,            -- Show blips for mechanics locations

	compatibilityMode = false,       -- prevents other scripts from modifying the fuel tank health to avoid random engine failure with BVA 2.01 (Downside is it disabled explosion prevention)

	randomTireBurstInterval = 0,     -- Number of minutes (statistically, not precisely) to drive above 22 mph before you get a tire puncture. 0=feature is disabled

	classDamageMultiplier = {
		[0] = 0.2, --	0: Compacts
		0.2, --	1: Sedans
		0.10, --	2: SUVs
		0.2, --	3: Coupes
		0.2, --	4: Muscle
		0.2, --	5: Sports Classics
		0.2, --	6: Sports
		0.2, --	7: Super
		0.10, --	8: Motorcycles
		0.10, --	9: Off-road
		0.10, --	10: Industrial
		0.2, --	11: Utility
		0.2, --	12: Vans
		0.2, --	13: Cycles
		0.2, --	14: Boats
		0.2, --	15: Helicopters
		0.2, --	16: Planes
		0.2, --	17: Service
		0.15, --	18: Emergency
		0.15, --	19: Military
		0.2, --	20: Commercial
		0.2  --	21: Trains
	}
}

Config.RequiredCops = {
	rob_npc = 1
}

Config.Keys = {
	["ESC"] = 322,
	["F1"] = 288,
	["F2"] = 289,
	["F3"] = 170,
	["F5"] = 166,
	["F6"] = 167,
	["F7"] = 168,
	["F8"] = 169,
	["F9"] = 56,
	["F10"] = 57,
	["~"] = 243,
	["1"] = 157,
	["2"] = 158,
	["3"] = 160,
	["4"] = 164,
	["5"] = 165,
	["6"] = 159,
	["7"] = 161,
	["8"] = 162,
	["9"] = 163,
	["-"] = 84,
	["="] = 83,
	["BACKSPACE"] = 177,
	["TAB"] = 37,
	["Q"] = 44,
	["W"] = 32,
	["E"] = 38,
	["R"] = 45,
	["T"] = 245,
	["Y"] = 246,
	["U"] = 303,
	["P"] = 199,
	["["] = 39,
	["]"] = 40,
	["ENTER"] = 18,
	["CAPS"] = 137,
	["A"] = 34,
	["S"] = 8,
	["D"] = 9,
	["F"] = 75,
	["G"] = 47,
	["H"] = 74,
	["K"] = 311,
	["L"] = 182,
	["LEFTSHIFT"] = 21,
	["Z"] = 20,
	["X"] = 73,
	["C"] = 26,
	["V"] = 0,
	["B"] = 29,
	["N"] = 249,
	["M"] = 244,
	[","] = 82,
	["."] = 81,
	["LEFTCTRL"] = 36,
	["LEFTALT"] = 19,
	["SPACE"] = 22,
	["RIGHTCTRL"] = 70,
	["HOME"] = 213,
	["PAGEUP"] = 10,
	["PAGEDOWN"] = 11,
	["DELETE"] = 178,
	["LEFT"] = 174,
	["RIGHT"] = 175,
	["TOP"] = 27,
	["DOWN"] = 173,
	["NENTER"] = 201,
	["N4"] = 108,
	["N5"] = 60,
	["N6"] = 107,
	["N+"] = 96,
	["N-"] = 97,
	["N7"] = 117,
	["N8"] = 61,
	["N9"] = 118
}

Config.DisabledTrunk = {
	[1] = `adder`,
}

Config.WeaponComponents = {
	0xFED0FD71,
	0xED265A1C,
	0x359B7AAE,
	0x65EA7EBB,
	0x721B079,
	0xD67B4F2D,
	0x359B7AAE,
	0xC304849A,
	0x31C4B22A,
	0x249A17D5,
	0x359B7AAE,
	0xC304849A,
	0xF8802ED9,
	0x7B0033B3,
	0xD4A969A,
	0x64F9C62B,
	0x359B7AAE,
	0xC304849A,
	0x1466CE6,
	0xCE8C0772,
	0x4A4965F3,
	0x47DE9258,
	0x65EA7EBB,
	0xAA8283BF,
	0x94F42D62,
	0x5ED6C128,
	0x43FD595B,
	0x8ED4BB70,
	0x65EA7EBB,
	0x21E34793,
	0x45A3B6BB,
	0x33BA12E8,
	0xC304849A,
	0x476E85FF,
	0xB92C6979,
	0xA9E9CAF4,
	0xC304849A,
}

Config.ItemsUniforms = {
	nurek = {
		male = {
			['tshirt_1'] = 123,
			['tshirt_2'] = 0, --
			['torso_1'] = 49,
			['torso_2'] = 0, --
			['arms'] = 17,
			['pants_1'] = 94,
			['pants_2'] = 0, --
			['shoes_1'] = 67,
			['shoes_2'] = 0, --
			['glasses_1'] = 26,
			['glasses_2'] = 0,
			['bags_1'] = 137,
			['bags_2'] = 0, --
		},
		female = {
			['tshirt_1'] = 123,
			['tshirt_2'] = 0, --
			['torso_1'] = 49,
			['torso_2'] = 0, --
			['arms'] = 17,
			['pants_1'] = 94,
			['pants_2'] = 0, --
			['shoes_1'] = 67,
			['shoes_2'] = 0, --
			['glasses_1'] = 26,
			['glasses_2'] = 0,
			['bags_1'] = 137,
			['bags_2'] = 0, --
		}
	},
}

Config.ModelDimensions = {
	min = 'vec3(-0.609518, -0.250000, -1.300000)',
	max = 'vec3(0.609981, 0.250000, 0.945000)'
}

Config.Blips = {
	{
		coords = { -1195.2007, -1577.4675, 4.6048 },
		sprite = 311,
		display = 4,
		scale = 0.7,
		color = 47,
		shortrange = true,
		name = "Siłownia",
	},
	{
		coords = { -1685.2050, -278.4342, 51.8623 },
		sprite = 305,
		display = 4,
		scale = 0.7,
		color = 0,
		shortrange = true,
		name = "Kościół",
	},
	{
		coords = { -549.9099, -195.2887, 38.2270 },
		sprite = 419,
		display = 4,
		scale = 0.9,
		color = 31,
		shortrange = true,
		name = "Urząd",
	},
	{
		coords = { -736.5374, -2275.6375, 13.4375 },
		sprite = 475,
		display = 4,
		scale = 0.8,
		color = 69,
		shortrange = true,
		name = "Apartamenty",
	},
	{
		coords = { -1006.8372, -475.1450, 50.0262 },
		sprite = 47,
		display = 4,
		scale = 0.8,
		color = 14,
		shortrange = true,
		name = "Psycholog",
	},
	{
		coords = { -1081.7291259766, -246.07032775879, 37.763347625732 },
		sprite = 606,
		display = 4,
		scale = 0.8,
		color = 37,
		shortrange = true,
		name = "Sklep Multimedialny",
	}
}

Config.PickupList = {
	`PICKUP_AMMO_BULLET_MP`,
	`PICKUP_AMMO_FIREWORK`,
	`PICKUP_AMMO_FLAREGUN`,
	`PICKUP_AMMO_GRENADELAUNCHER`,
	`PICKUP_AMMO_GRENADELAUNCHER_MP`,
	`PICKUP_AMMO_HOMINGLAUNCHER`,
	`PICKUP_AMMO_MG`,
	`PICKUP_AMMO_MINIGUN`,
	`PICKUP_AMMO_MISSILE_MP`,
	`PICKUP_AMMO_PISTOL`,
	`PICKUP_AMMO_RIFLE`,
	`PICKUP_AMMO_RPG`,
	`PICKUP_AMMO_SHOTGUN`,
	`PICKUP_AMMO_SMG`,
	`PICKUP_AMMO_SNIPER`,
	`PICKUP_ARMOUR_STANDARD`,
	`PICKUP_CAMERA`,
	`PICKUP_CUSTOM_SCRIPT`,
	`PICKUP_GANG_ATTACK_MONEY`,
	`PICKUP_HEALTH_SNACK`,
	`PICKUP_HEALTH_STANDARD`,
	`PICKUP_MONEY_CASE`,
	`PICKUP_MONEY_DEP_BAG`,
	`PICKUP_MONEY_MED_BAG`,
	`PICKUP_MONEY_PAPER_BAG`,
	`PICKUP_MONEY_PURSE`,
	`PICKUP_MONEY_SECURITY_CASE`,
	`PICKUP_MONEY_VARIABLE`,
	`PICKUP_MONEY_WALLET`,
	`PICKUP_PARACHUTE`,
	`PICKUP_PORTABLE_CRATE_FIXED_INCAR`,
	`PICKUP_PORTABLE_CRATE_UNFIXED`,
	`PICKUP_PORTABLE_CRATE_UNFIXED_INCAR`,
	`PICKUP_PORTABLE_CRATE_UNFIXED_INCAR_SMALL`,
	`PICKUP_PORTABLE_CRATE_UNFIXED_LOW_GLOW`,
	`PICKUP_PORTABLE_DLC_VEHICLE_PACKAGE`,
	`PICKUP_PORTABLE_PACKAGE`,
	`PICKUP_SUBMARINE`,
	`PICKUP_VEHICLE_ARMOUR_STANDARD`,
	`PICKUP_VEHICLE_CUSTOM_SCRIPT`,
	`PICKUP_VEHICLE_CUSTOM_SCRIPT_LOW_GLOW`,
	`PICKUP_VEHICLE_HEALTH_STANDARD`,
	`PICKUP_VEHICLE_HEALTH_STANDARD_LOW_GLOW`,
	`PICKUP_VEHICLE_MONEY_VARIABLE`,
	`PICKUP_VEHICLE_WEAPON_APPISTOL`,
	`PICKUP_VEHICLE_WEAPON_ASSAULTSMG`,
	`PICKUP_VEHICLE_WEAPON_COMBATPISTOL`,
	`PICKUP_VEHICLE_WEAPON_GRENADE`,
	`PICKUP_VEHICLE_WEAPON_MICROSMG`,
	`PICKUP_VEHICLE_WEAPON_MOLOTOV`,
	`PICKUP_VEHICLE_WEAPON_PISTOL`,
	`PICKUP_VEHICLE_WEAPON_PISTOL50`,
	`PICKUP_VEHICLE_WEAPON_SAWNOFF`,
	`PICKUP_VEHICLE_WEAPON_SMG`,
	`PICKUP_VEHICLE_WEAPON_SMOKEGRENADE`,
	`PICKUP_VEHICLE_WEAPON_STICKYBOMB`,
	`PICKUP_WEAPON_ADVANCEDRIFLE`,
	`PICKUP_WEAPON_APPISTOL`,
	`PICKUP_WEAPON_ASSAULTRIFLE`,
	`PICKUP_WEAPON_ASSAULTSHOTGUN`,
	`PICKUP_WEAPON_ASSAULTSMG`,
	`PICKUP_WEAPON_AUTOSHOTGUN`,
	`PICKUP_WEAPON_BAT`,
	`PICKUP_WEAPON_BATTLEAXE`,
	`PICKUP_WEAPON_BOTTLE`,
	`PICKUP_WEAPON_BULLPUPRIFLE`,
	`PICKUP_WEAPON_BULLPUPSHOTGUN`,
	`PICKUP_WEAPON_CARBINERIFLE`,
	`PICKUP_WEAPON_COMBATMG`,
	`PICKUP_WEAPON_COMBATPDW`,
	`PICKUP_WEAPON_COMBATPISTOL`,
	`PICKUP_WEAPON_COMPACTLAUNCHER`,
	`PICKUP_WEAPON_COMPACTRIFLE`,
	`PICKUP_WEAPON_CROWBAR`,
	`PICKUP_WEAPON_DAGGER`,
	`PICKUP_WEAPON_DBSHOTGUN`,
	`PICKUP_WEAPON_FIREWORK`,
	`PICKUP_WEAPON_FLAREGUN`,
	`PICKUP_WEAPON_FLASHLIGHT`,
	`PICKUP_WEAPON_GRENADE`,
	`PICKUP_WEAPON_GRENADELAUNCHER`,
	`PICKUP_WEAPON_GUSENBERG`,
	`PICKUP_WEAPON_GOLFCLUB`,
	`PICKUP_WEAPON_HAMMER`,
	`PICKUP_WEAPON_HATCHET`,
	`PICKUP_WEAPON_HEAVYPISTOL`,
	`PICKUP_WEAPON_HEAVYSHOTGUN`,
	`PICKUP_WEAPON_HEAVYSNIPER`,
	`PICKUP_WEAPON_HOMINGLAUNCHER`,
	`PICKUP_WEAPON_KNIFE`,
	`PICKUP_WEAPON_KNUCKLE`,
	`PICKUP_WEAPON_MACHETE`,
	`PICKUP_WEAPON_MACHINEPISTOL`,
	`PICKUP_WEAPON_MARKSMANPISTOL`,
	`PICKUP_WEAPON_MARKSMANRIFLE`,
	`PICKUP_WEAPON_MG`,
	`PICKUP_WEAPON_MICROSMG`,
	`PICKUP_WEAPON_MINIGUN`,
	`PICKUP_WEAPON_MINISMG`,
	`PICKUP_WEAPON_MOLOTOV`,
	`PICKUP_WEAPON_MUSKET`,
	`PICKUP_WEAPON_NIGHTSTICK`,
	`PICKUP_WEAPON_PETROLCAN`,
	`PICKUP_WEAPON_PIPEBOMB`,
	`PICKUP_WEAPON_PISTOL`,
	`PICKUP_WEAPON_PISTOL50`,
	`PICKUP_WEAPON_POOLCUE`,
	`PICKUP_WEAPON_PROXMINE`,
	`PICKUP_WEAPON_PUMPSHOTGUN`,
	`PICKUP_WEAPON_RAILGUN`,
	`PICKUP_WEAPON_REVOLVER`,
	`PICKUP_WEAPON_RPG`,
	`PICKUP_WEAPON_SAWNOFFSHOTGUN`,
	`PICKUP_WEAPON_SMG`,
	`PICKUP_WEAPON_SMOKEGRENADE`,
	`PICKUP_WEAPON_SNIPERRIFLE`,
	`PICKUP_WEAPON_SNSPISTOL`,
	`PICKUP_WEAPON_SPECIALCARBINE`,
	`PICKUP_WEAPON_STICKYBOMB`,
	`PICKUP_WEAPON_STUNGUN`,
	`PICKUP_WEAPON_SWITCHBLADE`,
	`PICKUP_WEAPON_VINTAGEPISTOL`,
	`PICKUP_WEAPON_WRENCH`,
	`PICKUP_WEAPON_RAYCARBINE`,
}

Config.VehicleClassDisable = {
	[0] = true,
	[1] = true,
	[2] = true,
	[3] = true,
	[4] = true,
	[5] = true,
	[6] = true,
	[7] = true,
	[8] = false,
	[9] = true,
	[10] = true,
	[11] = true,
	[12] = true,
	[13] = false,
	[14] = false,
	[15] = false,
	[16] = false,
	[17] = true,
	[18] = true,
	[19] = false
}

Config.PedsBlacklist = {
	GetHashKey('a_m_m_paparazzi_01'),
	GetHashKey('cs_martinmadrazo'),
	GetHashKey('cs_siemonyetarian'),
	GetHashKey('cs_dom'),
	GetHashKey('a_m_m_mexlabor_01'),
	GetHashKey('a_m_m_genfat_01'),
	GetHashKey('a_m_m_malibu_01'),
	GetHashKey('a_m_m_salton_02'),
	GetHashKey('a_m_m_socenlat_01'),
	GetHashKey('a_m_o_acult_01'),
	GetHashKey('a_m_o_soucent_01'),
	GetHashKey('s_m_m_trucker_01'),
	GetHashKey('s_m_m_gaffer_01'),
	GetHashKey('cs_lestercrest'),
	GetHashKey('s_m_m_dockwork_01'),
	GetHashKey('a_m_o_tramp_01'),
	GetHashKey('s_m_m_movspace_01'),
	GetHashKey('a_m_y_genstreet_01'),
	GetHashKey('s_m_y_chef_01'),
	GetHashKey('u_m_y_prisoner_01'),
	GetHashKey('cs_bankman'),
	GetHashKey('a_f_m_soucentmc_01'),
	GetHashKey('s_m_m_armoured_01'),
	GetHashKey('cs_mrk'),
	GetHashKey('s_m_m_highsec_01'),
	GetHashKey('s_m_m_strpreach_01'),
	GetHashKey('ig_lestercrest_2'),
	GetHashKey('g_m_m_chicold_01'),
	GetHashKey('s_m_m_paramedic_01'),
	GetHashKey('a_m_m_og_boss_01'),
	GetHashKey('s_m_y_waretech_01'),
	GetHashKey('U_M_M_BankMan'),
	GetHashKey('a_c_boar'),
	GetHashKey('a_c_cat_01'),
	GetHashKey('a_c_chickenhawk'),
	GetHashKey('a_c_chimp'),
	GetHashKey('a_c_chop'),
	GetHashKey('a_c_cormorant'),
	GetHashKey('a_c_cow'),
	GetHashKey('a_c_coyote'),
	GetHashKey('a_c_crow'),
	GetHashKey('a_c_deer'),
	GetHashKey('a_c_dolphin'),
	GetHashKey('a_c_fish'),
	GetHashKey('a_c_hen'),
	GetHashKey('a_c_humpback'),
	GetHashKey('a_c_husky'),
	GetHashKey('a_c_killerwhale'),
	GetHashKey('a_c_mtlion'),
	GetHashKey('a_c_pig'),
	GetHashKey('a_c_pigeon'),
	GetHashKey('a_c_poodle'),
	GetHashKey('a_c_pug'),
	GetHashKey('a_c_rabbit_01'),
	GetHashKey('a_c_rat'),
	GetHashKey('a_c_retriever'),
	GetHashKey('a_c_rhesus'),
	GetHashKey('a_c_rottweiler'),
	GetHashKey('a_c_seagull'),
	GetHashKey('a_c_sharkhammer'),
	GetHashKey('a_c_sharktiger'),
	GetHashKey('a_c_shepherd'),
	GetHashKey('a_c_stingray'),
	GetHashKey('a_c_westy'),
	GetHashKey('a_m_y_busicas_01'),
	GetHashKey('a_m_y_genstreet_01'),
	GetHashKey('a_m_y_mexthug_01'),
	GetHashKey('s_m_m_gaffer_01'),
	GetHashKey('csb_mweather'),
	GetHashKey('a_m_y_business_02'),
	GetHashKey('s_m_y_cop_01'),
	GetHashKey('mp_m_securoguard_01'),
	GetHashKey('s_m_m_doctor_01'),
	GetHashKey('mp_m_freemode_01'),
	GetHashKey('mp_f_freemode_01'),
	GetHashKey('a_m_y_cyclist_01'),
	GetHashKey('a_m_y_soucent_02'),
	GetHashKey('s_m_m_autoshop_02'),
	GetHashKey('a_m_m_og_boss_01'),
	GetHashKey('a_m_m_mlcrisis_01'),
	GetHashKey('a_m_y_musclbeac_02'),
	GetHashKey('s_f_m_shop_high'),
	GetHashKey('s_m_m_hairdress_01'),
	GetHashKey('u_m_y_tattoo_01'),
	GetHashKey('mp_g_m_pros_01'),
	GetHashKey('s_m_y_dealer_01'),
	GetHashKey('cs_martinmadrazo'),
	GetHashKey('u_m_y_rsranger_01'),
	GetHashKey('a_f_y_genhot_01'),
	GetHashKey('mp_m_shopkeep_01'),
	GetHashKey('s_m_m_ammucountry'),
	GetHashKey('u_m_y_proldriver_01'),
	GetHashKey('ig_ramp_mex'),
	GetHashKey('ig_lifeinvad_01'),
	GetHashKey('s_m_m_paramedic_01'),
	GetHashKey('g_m_y_famca_01'),
	GetHashKey('mp_m_waremech_01'),
}

Config.localMedicSpawn = {
	{ coords = vector3(1821.5941162109, 3662.5495605469, 33.966094970703),  heading = 148.9545, black = false, label = 'Skorzystaj z usług', hospital = 1 }, -- sandy
	{ coords = vector3(-248.43270874023, 6331.94921875, 32.426078796387),  heading = 183.0911, black = false, label = 'Skorzystaj z usług', hospital = 2 }, -- paleto
	{ coords = vector3(1146.1635, -1539.6763, 35.0330), heading = 264.8765, black = false, label = 'Skorzystaj z usług', hospital = 3 }, -- ls
	{ coords = vector3(1142.0000, -1539.6619, 39.5036), heading = 354.7784, black = false, label = 'Skorzystaj z usług', hospital = 4 }, -- ls #2
	{ coords = vector3(1445.4833, 6333.2061, 23.8722),  heading = 89.9717,  black = true,  label = 'Skorzystaj z usług' },
	{ coords = vector3(1540.8613, 3596.9165, 35.4525),  heading = 209.6921, black = true,  label = 'Skorzystaj z usług' },
	{ coords = vector3(-546.0450, -1694.2493, 19.4975), heading = 29.4786,  black = true,  label = 'Skorzystaj z usług' }
}

Config.localGovermentSpawn = {
	-- {coords = vec3(-57.1620, -1099.0055, 26.4225), heading = 26.7516, policealert = false, label = 'Zakup kontrakt'},
	{ coords = vec3(-1101.0463867188, -830.30145263672, 19.313339233398), heading = 125.3672, policealert = true, label = 'Zadzwoń dzwonkiem' },
	{ coords = vec3(387.87301635742, -1606.5065917969, 29.759468078613), heading = 318.3672, policealert = true, label = 'Zadzwoń dzwonkiem' },
}

Config.PedHeistSpawns = {
	{coords = vec3(-635.8096, 44.2130, 42.697), model = `cs_mrk`, lombard_menu_main = true, heading = 92.4130},
	{coords = vec3(-1245.6246, 376.3363, 75.3457), model = `a_m_y_mexthug_01`, lombard_menu_containers = true, heading = 25.3438},
	-- {coords = vec3(1408.5220, -2221.1409, 61.8128), model = `a_m_y_mexthug_01`, lombard_menu_houses = true, heading = 301.8582},
	-- {coords = vec3(464.3094, -700.8885, 27.5265), model = `a_m_y_mexthug_01`, lombard_menu_vangelico = true, heading = 90.2596},

	{coords = vec3(1271.9281005859, -1712.1124267578, 54.771457672119), model = `s_m_m_strpreach_01`, money_menu = true, heading = 15.0753},
}

Config.OneBagInInventory = false

Config.BackpackStorage = {
	slots = 16,
	weight = 100000
}

Strings = {
	action_incomplete = 'Akcja zakończona niepowodzeniem!',
	one_backpack_only = 'Możesz mieć jedną torbe!',
	backpack_in_backpack = 'Nie możesz umieścić torby wewnątrz innej torby!',
}

Config.MedicToUse = 2

Config.MaxDistance = 2.5
Config.Debug = false

Config.Visual = {
	icon = 'fas fa-chair',
	label = 'Usiądź',
	notification = 'Ktoś siedzi na tym krześle',
	error = 'Siedzisz już tutaj!'
}

Config.Sitable = {
	-- BENCH
	prop_bench_01a              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_01b              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_01c              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_02               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_03               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_04               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_06               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_05               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_08               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_09               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.31, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_10               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_bench_11               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_fib_3b_bench           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_bench01             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_wait_bench_01          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- CHAIR
	v_club_stagechair           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_heist_off_chair    = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_hei_skid_chair     = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_01a              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_01b              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_02               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_03               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_04a              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_04b              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	apa_mp_h_din_chair_12       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_06               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_05               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_08               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_09               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chair_10               = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_chateau_chair_01       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_clown_chair            = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_cs_office_chair        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_direct_chair_01        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_direct_chair_02        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_gc_chair02             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_01           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_03           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_04           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_04b          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_04_s         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_off_chair_05           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.45, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_old_deck_chair         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_old_wood_chair         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rock_chair_01          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_skid_chair_01          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_skid_chair_02          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_skid_chair_03          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_sol_chair              = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_wheelchair_01          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_wheelchair_01_s        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_armchair_01_s             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_clb_officechair_s         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_dinechair_01_s            = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_ilev_p_easychair_s        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_soloffchair_s             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_yacht_chair_01_s          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_club_officechair          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_corp_bk_chair3            = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_corp_cd_chair             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_corp_offchair             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_chair02_ped          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_hd_chair             = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_p_easychair          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ret_gc_chair03            = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_farm_chair01        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_04_chr           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.56, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_05_chr           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_06_chr           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_leath_chr            = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_01_chr_a         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_01_chr_b         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_02_chr           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_03b_chr          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_table_03_chr           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_torture_ch_01          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_fh_dineeamesa        = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_res_m_armchair            = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.1, leftOffset = 0.0 },
	xm_prop_x17_avengerchair_02 = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.1, forwardOffset = 0.0, leftOffset = 0.0 },


	v_ilev_tort_stool      = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_fh_kitchenstool = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- SEAT
	hei_prop_yah_seat_01   = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_yah_seat_02   = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	hei_prop_yah_seat_03   = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_waiting_seat_01   = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_yacht_seat_01     = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_yacht_seat_02     = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_yacht_seat_03     = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_hobo_seat_01      = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.65, forwardOffset = 0.0, leftOffset = 0.0 },

	-- COUCH
	prop_rub_couch01       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	miss_rub_couch_01      = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_farm_couch01   = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_ld_farm_couch02   = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rub_couch02       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rub_couch03       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_rub_couch04       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- SOFA
	p_lev_sofa_s           = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_res_sofa_l_s         = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_v_med_p_sofa_s       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	p_yacht_sofa_01_s      = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_ilev_m_sofa          = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_res_tre_sofa_s       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_tre_sofa_mess_a_s    = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_tre_sofa_mess_b_s    = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_tre_sofa_mess_c_s    = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- MISC
	prop_roller_car_01     = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	prop_roller_car_02     = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

	-- CUSTOM
	v_ret_gc_chair02       = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },
	v_serv_ct_chair02      = { scenario = 'PROP_HUMAN_SEAT_BENCH', verticalOffset = -0.5, forwardOffset = 0.0, leftOffset = 0.0 },

}

Config.Interactables = {
	'prop_bench_01a',
	'prop_bench_01b',
	'prop_bench_01c',
	'prop_bench_02',
	'prop_bench_03',
	'prop_bench_04',
	'prop_bench_05',
	'prop_bench_06',
	'prop_bench_05',
	'prop_bench_08',
	'prop_bench_09',
	'prop_bench_10',
	'prop_bench_11',
	'prop_fib_3b_bench',
	'prop_ld_bench01',
	'prop_wait_bench_01',
	'hei_prop_heist_off_chair',
	'hei_prop_hei_skid_chair',
	'prop_chair_01a',
	'prop_chair_01b',
	'prop_chair_02',
	'prop_chair_03',
	'prop_chair_04a',
	'prop_chair_04b',
	'prop_chair_05',
	'prop_chair_06',
	'prop_chair_05',
	'prop_chair_08',
	'prop_chair_09',
	'prop_chair_10',
	'v_club_stagechair',
	'prop_chateau_chair_01',
	'prop_clown_chair',
	'prop_cs_office_chair',
	'prop_direct_chair_01',
	'prop_direct_chair_02',
	'prop_gc_chair02',
	'prop_off_chair_01',
	'prop_off_chair_03',
	'prop_off_chair_04',
	'prop_off_chair_04b',
	'prop_off_chair_04_s',
	'prop_off_chair_05',
	'prop_old_deck_chair',
	'prop_old_wood_chair',
	'prop_rock_chair_01',
	'prop_skid_chair_01',
	'prop_skid_chair_02',
	'prop_skid_chair_03',
	'prop_sol_chair',
	'prop_wheelchair_01',
	'prop_wheelchair_01_s',
	'p_armchair_01_s',
	'p_clb_officechair_s',
	'p_dinechair_01_s',
	'p_ilev_p_easychair_s',
	'p_soloffchair_s',
	'p_yacht_chair_01_s',
	'v_club_officechair',
	'v_corp_bk_chair3',
	'v_corp_cd_chair',
	'v_corp_offchair',
	'v_ilev_chair02_ped',
	'v_ilev_hd_chair',
	'v_ilev_p_easychair',
	'v_ret_gc_chair03',
	'prop_ld_farm_chair01',
	'prop_table_04_chr',
	'prop_table_05_chr',
	'prop_table_06_chr',
	'v_ilev_leath_chr',
	'prop_table_01_chr_a',
	'prop_table_01_chr_b',
	'prop_table_02_chr',
	'prop_table_03b_chr',
	'prop_table_03_chr',
	'prop_torture_ch_01',
	'v_ilev_fh_dineeamesa',
	'v_ilev_fh_kitchenstool',
	'v_ilev_tort_stool',
	'v_ilev_fh_kitchenstool',
	'v_ilev_fh_kitchenstool',
	'v_ilev_fh_kitchenstool',
	'v_ilev_fh_kitchenstool',
	'hei_prop_yah_seat_01',
	'hei_prop_yah_seat_02',
	'hei_prop_yah_seat_03',
	'prop_waiting_seat_01',
	'prop_yacht_seat_01',
	'prop_yacht_seat_02',
	'prop_yacht_seat_03',
	'prop_hobo_seat_01',
	'prop_rub_couch01',
	'miss_rub_couch_01',
	'prop_ld_farm_couch01',
	'prop_ld_farm_couch02',
	'prop_rub_couch02',
	'prop_rub_couch03',
	'prop_rub_couch04',
	'p_lev_sofa_s',
	'p_res_sofa_l_s',
	'p_v_med_p_sofa_s',
	'p_yacht_sofa_01_s',
	'v_ilev_m_sofa',
	'v_res_tre_sofa_s',
	'v_tre_sofa_mess_a_s',
	'v_tre_sofa_mess_b_s',
	'v_tre_sofa_mess_c_s',
	'prop_roller_car_01',
	'prop_roller_car_02',
	-- Custom
	'v_ret_gc_chair02',
	'v_serv_ct_chair02',
	'apa_mp_h_din_chair_12',
	'xm_prop_x17_avengerchair_02',
	'v_res_m_armchair',
}

Config.BlockedIcon = "❌"
Config.BlockedIconSize = 0.015
Config.BlockedIconColor = { r = 255, g = 50, b = 50, a = 255 }

Config.RaycastDistance = 200.0
Config.UpdateInterval = 10

Config.nurekItem = 'nurek'

Config.pedsMale = {
    [`mp_m_freemode_01`] = true,
}

Config.pedsFemale = {
    [`mp_f_freemode_01`] = true,
}

Config.maleScubaVariation = 124
Config.femaleScubaVariation = 154
Config.maleScubaMaskVariation = 26
Config.femaleScubaMaskVariation = 28

Config.fulltank = 400

Config.ipls = {
	'h4_aa_guns',
    'h4_aa_guns_lod',
    'h4_beach',
    'h4_beach_lod',
    'h4_beach_slod',
    'h4_beach_props',
    'h4_beach_props_lod',
    'h4_beach_props_slod',
    'h4_beach_party',
    'h4_beach_props_party',
    'h4_beach_party_lod',
    'h4_beach_bar_props',
    'h4_island_padlock_props',
    'h4_islandx_barrack_hatch',
    'h4_islandx_barrack_props',
    'h4_islandx_barrack_props_lod',
    'h4_islandx_barrack_props_slod',
    'h4_islandxcanal_props',
    'h4_islandxcanal_props_lod',
    'h4_islandxcanal_props_slod',
    'h4_islandx_mansion_entrance_fence',
    'h4_islandx_mansion_guardfence',
    'h4_islandx_mansion_lights',
    'h4_islandx_mansion_lod',
    'h4_islandx_mansion_slod',
    'h4_islandx_mansion_b',
    'h4_islandx_mansion_b_side_fence',
    'h4_islandx_mansion_b_lod',
    'h4_islandx_mansion_b_slod',
    'h4_islandx_mansion_props',
    'h4_islandx_mansion_props_lod',
    'h4_islandx_mansion_props_slod',
    'h4_islandx_mansion_vault',
    'h4_islandx_mansion_vault_lod',
    'h4_islandx_mansion_lockup_01',
    'h4_islandx_mansion_lockup_01_lod',
    'h4_islandx_mansion_lockup_02',
    'h4_islandx_mansion_lockup_02_lod',
    'h4_islandx_mansion_lockup_03',
    'h4_islandx_mansion_lockup_03_lod',
    'h4_islandx_mansion_office',
    'h4_islandx_mansion_office_lod',
    'h4_islandx',
    'h4_islandx_props',
    'h4_islandx_props_lod',
    'h4_islandx_terrain_01',
    'h4_islandx_terrain_02',
    'h4_islandx_terrain_03',
    'h4_islandx_terrain_04',
    'h4_islandx_terrain_05',
    'h4_islandx_terrain_06',
    'h4_islandx_terrain_props_05_a',
    'h4_islandx_terrain_props_05_b',
    'h4_islandx_terrain_props_05_c',
    'h4_islandx_terrain_props_05_d',
    'h4_islandx_terrain_props_05_e',
    'h4_islandx_terrain_props_05_f',
    'h4_islandx_terrain_props_06_a',
    'h4_islandx_terrain_props_06_b',
    'h4_islandx_terrain_props_06_c',
    'h4_islandx_terrain_01_lod',
    'h4_islandx_terrain_02_lod',
    'h4_islandx_terrain_03_lod',
    'h4_islandx_terrain_04_lod',
    'h4_islandx_terrain_05_lod',
    'h4_islandx_terrain_06_lod',
    'h4_islandx_terrain_props_05_a_lod',
    'h4_islandx_terrain_props_05_b_lod',
    'h4_islandx_terrain_props_05_c_lod',
    'h4_islandx_terrain_props_05_d_lod',
    'h4_islandx_terrain_props_05_e_lod',
    'h4_islandx_terrain_props_05_f_lod',
    'h4_islandx_terrain_props_06_a_lod',
    'h4_islandx_terrain_props_06_b_lod',
    'h4_islandx_terrain_props_06_c_lod',
    'h4_islandx_terrain_01_slod',
    'h4_islandx_terrain_02_slod',
    'h4_islandx_terrain_04_slod',
    'h4_islandx_terrain_05_slod',
    'h4_islandx_terrain_06_slod',
    'h4_islandx_terrain_props_05_d_slod',
    'h4_islandx_terrain_props_05_e_slod',
    'h4_islandx_terrain_props_05_f_slod',
    'h4_islandx_terrain_props_06_a_slod',
    'h4_islandx_terrain_props_06_b_slod',
    'h4_islandx_terrain_props_06_c_slod',
    'h4_mph4_airstrip',
    'h4_mph4_airstrip_interior_0_airstrip_hanger',
    'h4_mph4_beach',
    'h4_mph4_dock',
    'h4_mph4_island',
    'h4_mph4_island_long_0',
    'h4_mph4_island_strm_0',
    'h4_mph4_island_lod',
    'h4_mph4_island_placement',
    'h4_mph4_island_ne_placement',
    'h4_mph4_island_nw_placement',
    'h4_mph4_island_se_placement',
    'h4_mph4_island_sw_placement',
    'h4_mph4_mansion',
    'h4_mph4_mansion_strm_0',
    'h4_mph4_mansion_b',
    'h4_mph4_mansion_b_strm_0',
    'h4_mph4_wtowers',
    'h4_mph4_terrain_01',
    'h4_mph4_terrain_01_grass_0',
    'h4_mph4_terrain_01_grass_1',
    'h4_mph4_terrain_01_long_0',
    'h4_mph4_terrain_02',
    'h4_mph4_terrain_02_grass_0',
    'h4_mph4_terrain_02_grass_1',
    'h4_mph4_terrain_02_grass_2',
    'h4_mph4_terrain_02_grass_3',
    'h4_mph4_terrain_03',
    'h4_mph4_terrain_04',
    'h4_mph4_terrain_04_grass_0',
    'h4_mph4_terrain_04_grass_1',
    'h4_mph4_terrain_05',
    'h4_mph4_terrain_05_grass_0',
    'h4_mph4_terrain_06',
    'h4_mph4_terrain_06_strm_0',
    'h4_mph4_terrain_lod',
    'h4_mph4_terrain_occ_00',
    'h4_mph4_terrain_occ_01',
    'h4_mph4_terrain_occ_02',
    'h4_mph4_terrain_occ_03',
    'h4_mph4_terrain_occ_04',
    'h4_mph4_terrain_occ_05',
    'h4_mph4_terrain_occ_06',
    'h4_mph4_terrain_occ_07',
    'h4_mph4_terrain_occ_08',
    'h4_mph4_terrain_occ_09',
    'h4_ne_ipl_00',
    'h4_ne_ipl_01',
    'h4_ne_ipl_02',
    'h4_ne_ipl_03',
    'h4_ne_ipl_04',
    'h4_ne_ipl_05',
    'h4_ne_ipl_06',
    'h4_ne_ipl_07',
    'h4_ne_ipl_08',
    'h4_ne_ipl_09',
    'h4_ne_ipl_00_lod',
    'h4_ne_ipl_01_lod',
    'h4_ne_ipl_02_lod',
    'h4_ne_ipl_03_lod',
    'h4_ne_ipl_04_lod',
    'h4_ne_ipl_05_lod',
    'h4_ne_ipl_06_lod',
    'h4_ne_ipl_07_lod',
    'h4_ne_ipl_08_lod',
    'h4_ne_ipl_09_lod',
    'h4_ne_ipl_00_slod',
    'h4_ne_ipl_01_slod',
    'h4_ne_ipl_02_slod',
    'h4_ne_ipl_03_slod',
    'h4_ne_ipl_04_slod',
    'h4_ne_ipl_05_slod',
    'h4_ne_ipl_06_slod',
    'h4_ne_ipl_07_slod',
    'h4_ne_ipl_08_slod',
    'h4_ne_ipl_09_slod',
    'h4_nw_ipl_00',
    'h4_nw_ipl_01',
    'h4_nw_ipl_02',
    'h4_nw_ipl_03',
    'h4_nw_ipl_04',
    'h4_nw_ipl_05',
    'h4_nw_ipl_06',
    'h4_nw_ipl_07',
    'h4_nw_ipl_08',
    'h4_nw_ipl_09',
    'h4_nw_ipl_00_lod',
    'h4_nw_ipl_01_lod',
    'h4_nw_ipl_02_lod',
    'h4_nw_ipl_03_lod',
    'h4_nw_ipl_04_lod',
    'h4_nw_ipl_05_lod',
    'h4_nw_ipl_06_lod',
    'h4_nw_ipl_07_lod',
    'h4_nw_ipl_08_lod',
    'h4_nw_ipl_09_lod',
    'h4_nw_ipl_00_slod',
    'h4_nw_ipl_01_slod',
    'h4_nw_ipl_02_slod',
    'h4_nw_ipl_03_slod',
    'h4_nw_ipl_04_slod',
    'h4_nw_ipl_05_slod',
    'h4_nw_ipl_06_slod',
    'h4_nw_ipl_07_slod',
    'h4_nw_ipl_08_slod',
    'h4_nw_ipl_09_slod',
    'h4_se_ipl_00',
    'h4_se_ipl_01',
    'h4_se_ipl_02',
    'h4_se_ipl_03',
    'h4_se_ipl_04',
    'h4_se_ipl_05',
    'h4_se_ipl_06',
    'h4_se_ipl_07',
    'h4_se_ipl_08',
    'h4_se_ipl_09',
    'h4_se_ipl_00_lod',
    'h4_se_ipl_01_lod',
    'h4_se_ipl_02_lod',
    'h4_se_ipl_03_lod',
    'h4_se_ipl_04_lod',
    'h4_se_ipl_05_lod',
    'h4_se_ipl_06_lod',
    'h4_se_ipl_07_lod',
    'h4_se_ipl_08_lod',
    'h4_se_ipl_09_lod',
    'h4_se_ipl_00_slod',
    'h4_se_ipl_01_slod',
    'h4_se_ipl_02_slod',
    'h4_se_ipl_03_slod',
    'h4_se_ipl_04_slod',
    'h4_se_ipl_05_slod',
    'h4_se_ipl_06_slod',
    'h4_se_ipl_07_slod',
    'h4_se_ipl_08_slod',
    'h4_se_ipl_09_slod',
    'h4_sw_ipl_00',
    'h4_sw_ipl_01',
    'h4_sw_ipl_02',
    'h4_sw_ipl_03',
    'h4_sw_ipl_04',
    'h4_sw_ipl_05',
    'h4_sw_ipl_06',
    'h4_sw_ipl_07',
    'h4_sw_ipl_08',
    'h4_sw_ipl_09',
    'h4_sw_ipl_00_lod',
    'h4_sw_ipl_01_lod',
    'h4_sw_ipl_02_lod',
    'h4_sw_ipl_03_lod',
    'h4_sw_ipl_04_lod',
    'h4_sw_ipl_05_lod',
    'h4_sw_ipl_06_lod',
    'h4_sw_ipl_07_lod',
    'h4_sw_ipl_08_lod',
    'h4_sw_ipl_09_lod',
    'h4_sw_ipl_00_slod',
    'h4_sw_ipl_01_slod',
    'h4_sw_ipl_02_slod',
    'h4_sw_ipl_03_slod',
    'h4_sw_ipl_04_slod',
    'h4_sw_ipl_05_slod',
    'h4_sw_ipl_06_slod',
    'h4_sw_ipl_07_slod',
    'h4_sw_ipl_08_slod',
    'h4_sw_ipl_09_slod',
    'h4_ch2_mansion_final',
    'h4_islandx_checkpoint',
    'h4_islandx_checkpoint_lod',
    'h4_islandx_checkpoint_props',
    'h4_islandx_checkpoint_props_lod',
    'h4_islandx_checkpoint_props_slod',
    'h4_islandairstrip',
    'h4_islandairstrip_lod',
    'h4_islandairstrip_slod',
    'h4_islandairstrip_props',
    'h4_islandairstrip_props_lod',
    'h4_islandairstrip_props_slod',
    'h4_islandairstrip_propsb',
    'h4_islandairstrip_propsb_lod',
    'h4_islandairstrip_propsb_slod',
    'h4_islandairstrip_hangar_props',
    'h4_islandairstrip_hangar_props_lod',
    'h4_islandairstrip_hangar_props_slod',
    'h4_islandx_maindock',
    'h4_islandx_maindock_lod',
    'h4_islandx_maindock_slod',
    'h4_islandx_maindock_props',
    'h4_islandx_maindock_props_lod',
    'h4_islandx_maindock_props_slod',
    'h4_islandx_maindock_props_2',
    'h4_islandx_maindock_props_2_lod',
    'h4_islandx_maindock_props_2_slod',
    'h4_islandxdock',
    'h4_islandxdock_lod',
    'h4_islandxdock_slod',
    'h4_islandxdock_props',
    'h4_islandxdock_props_lod',
    'h4_islandxdock_props_slod',
    'h4_islandxdock_props_2',
    'h4_islandxdock_props_2_lod',
    'h4_islandxdock_props_2_slod',
    'h4_islandxdock_water_hatch',
    'h4_islandxtower',
    'h4_islandxtower_lod',
    'h4_islandxtower_slod',
    'h4_islandxtower_veg',
    'h4_islandxtower_veg_lod',
    'h4_islandxtower_veg_slod',
    'island_lodlights',
    'island_distantlights',
    'h4_islandx_mansion',
    'h4_mansion_gate_closed',
    'h4_islandairstrip_doorsopen',
    'h4_islandairstrip_doorsopen_lod',

    -- OPTIONAL IPLs (Bloatware, uncomment only if you know what are)
    -- 'h4_yacht',
    -- 'h4_yacht_long_0',
    -- 'h4_yacht_strm_0',
    -- 'h4_yacht_critical_0',
    -- 'h4_int_placement_h4',
    -- 'h4_int_placement_h4_interior_0_int_sub_h4_milo_',
    -- 'h4_int_placement_h4_interior_1_dlc_int_02_h4_milo_',
    -- 'h4_clubposter_keinemusik',
    -- 'h4_clubposter_moodymann',
    -- 'h4_clubposter_palmstraxx',
    -- 'h4_mansion_remains_cage',
    -- 'h4_islandx_disc_strandedshark',
    -- 'h4_islandx_disc_strandedshark_lod',
    -- 'h4_islandx_disc_strandedwhale',
    -- 'h4_islandx_disc_strandedwhale_lod',
    -- 'h4_islandx_sea_mines',
    -- 'h4_boatblockers',
    -- 'h4_mansion_gate_broken',
    -- 'h4_underwater_gate_closed',
    -- 'h4_islandairstrip_doorsclosed',
    -- 'h4_islandairstrip_doorsclosed_lod',
    -- 'h4_islandx_yacht_01',
    -- 'h4_islandx_yacht_01_int',
    -- 'h4_islandx_yacht_01_lod',
    -- 'h4_islandx_yacht_02',
    -- 'h4_islandx_yacht_02_int',
    -- 'h4_islandx_yacht_03',
    -- 'h4_islandx_yacht_03_int',
}