Config = {}

Config.prefix = {
	["founder"] = "Zarząd",
	["developer"] = "Developer",
    ["managment"] = "Managment",
	['headadmin'] = "Head Admin",
	['admin'] = "Admin",
	['trialadmin'] = "Trial Admin",
	['seniormod'] = "Senior Moderator",
	['mod'] = "Moderator",
	['moderator'] = "Moderator",
	['trialmod'] = "Trial Moderator",
	['support'] = "Support",
	['trialsupport'] = "Trial Support",
	['helper'] = "Helper",
	['trialhelper'] = "Trial Helper",
	['vip'] = "VIP",
	['svip'] = "SVIP",
	['elite'] = "ELITE",
}

Config.group = {
	['founder'] = {255, 215, 0},
	['developer'] = {0, 191, 255},
	['managment'] = {255, 140, 0},
	['headadmin'] = {255, 0, 0},
	['admin'] = {0, 191, 255},
	['trialadmin'] = {100, 191, 255},
	['seniormod'] = {132, 112, 255},
	['mod'] = {150, 130, 255},
	['moderator'] = {132, 112, 255},
	['trialmod'] = {170, 150, 255},
	['support'] = {255, 200, 0},
	['trialsupport'] = {255, 220, 100},
	['helper'] = {255, 165, 0},
	['trialhelper'] = {255, 255, 0},
	['vip'] = {32, 72, 247},
	['svip'] = {161, 2, 189},
	['elite'] = {245, 201, 59},
	['user'] = {227, 230, 228}
}

Config.privatePrefix = {
	[""] = "Owner: ",
}

Config.privateColor = {
	[""] = {255, 255, 255},
}

Config.Substitution = {
	["$"] = "s",
    ["€"] = "e",
    [","] = "",
    [";"] = "",
    [":"] = "",
    ["*"] = "",
    ["_"] = "",
    ["|"] = "",
    ["/"] = "",
    ["<"] = "",
    [">"] = "",
    ["ß"] = "ss",
    ["&"] = "",
    ["+"] = "",
    ["¦"] = "",
    ["§"] = "s",
    ["°"] = "",
    ["#"] = "",
    ["@"] = "a",
    ["\""] = "",
    ["%("] = "",
    ["%)"] = "",
    ["="] = "",
    ["?"] = "",
    ["!"] = "",
    ["´"] = "",
    ["`"] = "",
    ["'"] = "",
    ["%^"] = "",
    ["~"] = "",
    ["%"] = "",
    ["]"] = "",
    ["{"] = "",
    ["}"] = "",
    ["£"] = "e",
    ["¨"] = "",
    ["ç"] = "c",
    ["¬"] = "",
    ["\\"] = "",
    ["1"] = "i",
    ["3"] = "e",
    ["4"] = "a",
    ["5"] = "s",
    ["0"] = "o",
}

Config.Blacklist = {
	"niga",
	"wavesrp",
	"trujcarp",
	"trujca",
	"trujcardm",
	"exile",
	"exilerp",
	"hyperp",
	"bettersiderp",
	"waitrp",
	"notrp",
	"aries",
	"xaries",
	"bitsu",
	"krzychubaza",
	"discord",
	"Hitler",
	"pedofil",
	"Hilter",
	"Himler",
	"Himmler",
	"Stalin",
	"Putin",
	"nigga",
	"n igga",
	"nig ga",
	"nigg a",
	"n igger",
	"ni gger",
	"nig ger",
	"nigge r",
	"pedal",
	"pedał",
	"pedała",
	"pedale",
	"simp",
	"faggot",
	"upośledzony",
	"upośledzona",
	"retarded",
	"czarnuch",
	"c wel",
	"cw el",
	"cwel",
	"cwe l",
	"czarnuh",
	"żyd",
	"zyd",
	"hitler",
	"jebac disa",
	"nygus",
	"ciota",
	"cioty",
	"cioto",
	"cwelu",
	"cwele",
	"czarnuchu",
	"niggerze",
	"nigerze",
	"nygusie",
	"karzeł",
	"karzel",
	"simpie",
	"pedalskie",
	"zydzie",
	"żydzie",
	"geju",
	"nigger",
	"n1gger",
	"n1gger",
	"n1ga",
	"nigga",
	"n1gga",
	"nigg3r",
	"nig3r",
	"shagged",
	"n199er",
	"n1993r",
	"fucking",
	"nygga",
	"nyger",
	"nyggerze",
	"nygerze",
	"fuckniggas", 
	"fucknigas", 
	"fuck niggas",
	"fuck nigas",
	"fucknyggas", 
	"fucknygas", 
	"fuck nyggas", 
	"fuck nygas", 
	"nyga", 
	"pedai",
	"p3dal",
	"p3dał",
	"murzyn",
	"murzynie",
	"h i t l e r",
	"s t a l i n",
	"p u t i n",
	"n i g g a",
	"n i g g e r",
	"p e d a ł",
	"p e d a l",
	"p e d a i",
	"s i m p",
	"d o w n",
	"f a g g o t",
	"u p o ś l e d z o n y",
	"c w e l",
	"c z a r n u c h",
	"ż y d",
	"z y d",
	"n y g u s",
	"c i o t a",
	"cfel",
	"cfelu",
	"c f e l"
}

Config.RemoveDescriptionItem = 'desc_remover'

Config.ReportsTopWebhook = "https://discord.com/api/webhooks/1459617645388107870/0erY4vJpXxqVGqpMnoFHOcMH2D6_3rdXZzC1a7b6hrm3LvrmKeOdK_XJCKst8ei9j6Y-"
Config.ReportsTopAutoSendInterval = 1