---------------------------------------------------------------------------------------
---------------------------------- GTA MODIFICATIONS ----------------------------------
---------------------------------------------------------------------------------------
-- All the base GTA modifications. You *probably* won't need to modify this file
-- unless you a nerd and know what you are going. In that case, have fun <3
---------------------------------------------------------------------------------------

Config.Mods = {}

Config.Mods.ItemsRequired = {
  repair = { itemName = "repair_kit", removeItem = true },
  performance = { itemName = "performance_part", removeItem = true },
  cosmetics = { itemName = "cosmetic_part", removeItem = true },
  stance = { itemName = "stancing_kit", removeItem = false },
  respray = { itemName = "respray_kit", removeItem = true },
  wheels = { itemName = "vehicle_wheels", removeItem = true },
  neonLights = { itemName = "lighting_controller", removeItem = true },
  headlights = { itemName = "lighting_controller", removeItem = true },
  tyreSmoke = { itemName = "tyre_smoke_kit", removeItem = true },
  bulletproofTyres = { itemName = "bulletproof_tyres", removeItem = true },
  extras = { itemName = "extras_kit", removeItem = true }
}

Config.Mods.Performance = {
  { modType = 11, name = "Silnik", overrideOptions = {
    { modIndex = 0, name = "Silnik, poziom 1" },
    { modIndex = 1, name = "Silnik, poziom 2" },
    { modIndex = 2, name = "Silnik, poziom 3" },
    { modIndex = 3, name = "Silnik, poziom 4" }
  } },
  { modType = 12, name = "Hamulce", overrideOptions = {
    { modIndex = 0, name = "Hamulce uliczne" },
    { modIndex = 1, name = "Hamulce sportowe" },
    { modIndex = 2, name = "Hamulce wyścigowe" }
  } },
  { modType = 13, name = "Skrzynia biegów", overrideOptions = {
    { modIndex = 0, name = "Skrzynia uliczna" },
    { modIndex = 1, name = "Skrzynia sportowa" },
    { modIndex = 2, name = "Skrzynia wyścigowa" }
  } },
  { modType = 15, name = "Zawieszenie", overrideOptions = {
    { modIndex = 0, name = "Obniżone zawieszenie" },
    { modIndex = 1, name = "Zawieszenie uliczne" },
    { modIndex = 2, name = "Zawieszenie sportowe" },
    { modIndex = 3, name = "Zawieszenie wyścigowe" }
  } },
  -- { modType = 16, name = "Armour", overrideOptions = {
  --   { modIndex = 0, name = "Armor Upgrade 20%" },
  --   { modIndex = 1, name = "Armor Upgrade 40%" },
  --   { modIndex = 2, name = "Armor Upgrade 60%" },
  --   { modIndex = 3, name = "Armor Upgrade 80%" },
  --   { modIndex = 4, name = "Armor Upgrade 100%" }
  -- } },
  { modType = 18, name = "Turbosprężarka", toggle = true } 
}

Config.Mods.Cosmetics = {
  { modType = 0, name = "Spoilery" },
  { modType = 1, name = "Zderzak przedni" },
  { modType = 2, name = "Zderzak tylny" },
  { modType = 3, name = "Progi boczne" },
  { modType = 4, name = "Wydech" },
  { modType = 5, name = "Nadwozie" },
  { modType = 6, name = "Atrapa chłodnicy" },
  { modType = 7, name = "Maska" },
  { modType = 8, name = "Lewe skrzydło" },
  { modType = 9, name = "Prawe skrzydło" },
  { modType = 10, name = "Dach" },
  { modType = 14, name = "Klakson", ignorePriceMult = true },
  { modType = 19, name = "Subwoofer" },
  { modType = 21, name = "Hydraulika" },
  { modType = 25, name = "Ramki na tablicę" },
  { modType = 26, name = "Ozdobna tablica" },
  { modType = 27, name = "Wzór wykończenia" },
  { modType = 28, name = "Ozdoby" },
  { modType = 29, name = "Deska rozdzielcza" },
  { modType = 30, name = "Wzór zegarów" },
  { modType = 31, name = "Głośniki drzwiowe" },
  { modType = 32, name = "Fotele" },
  { modType = 33, name = "Kierownica" },
  { modType = 34, name = "Dźwignia zmiany biegów" },
  { modType = 35, name = "Tabliczki" },
  { modType = 36, name = "System audio" },
  { modType = 37, name = "Bagażnik" },
  { modType = 38, name = "Hydraulika" },
  { modType = 39, name = "Blok silnika" },
  { modType = 40, name = "Filtr powietrza/Doładowanie" },
  { modType = 41, name = "Amortyzatory" },
  { modType = 42, name = "Nakładka na nadkola" },
  { modType = 43, name = "Anteny" },
  { modType = 44, name = "Wykończenie" },
  { modType = 45, name = "Zbiornik paliwa" },
  { modType = 46, name = "Lewe drzwi" },
  { modType = 47, name = "Prawe drzwi" },
  { modType = 48, name = "Naklejki" },
  { modType = 49, name = "Listwa świetlna" },

  -- Nazwane modyfikacje
  { modType = "LIVERY", name = "Malowanie" },
  { modType = "LIVERY_ROOF", name = "Malowanie dachu" },
  { modType = "PLATE_INDEX", name = "Tablice rejestracyjne", ignorePriceMult = true },
  { modType = "WINDOW_TINT", name = "Przyciemnienie szyb", ignorePriceMult = true }
}

Config.Mods.PlateIndexes = {
  { modIndex = 0, name = "Niebieskie na białym" },
  { modIndex = 1, name = "Żółte na czarnym" },
  { modIndex = 2, name = "Żółte na niebieskim" },
  { modIndex = 3, name = "Niebieskie na białym" },  -- Powtórzone celowo
  { modIndex = 4, name = "Niebieskie na białym" },  -- Powtórzone celowo
  { modIndex = 5, name = "North Yankton" },  -- Nazwa własna

  -- mp2023_02 (Chop Shop) tylko
  { modIndex = 6, name = "eCola" },  -- Marka
  { modIndex = 7, name = "Las Venturas" },  -- Nazwa miasta z gry
  { modIndex = 8, name = "Liberty City" },  -- Nazwa miasta z gry
  { modIndex = 9, name = "Los Santos Car Meet" },  -- Wydarzenie
  { modIndex = 10, name = "Los Santos Panic" },  -- Nazwa własna
  { modIndex = 11, name = "Los Santos Pounders" },  -- Nazwa własna
  { modIndex = 12, name = "Sprunk" }  -- Marka
}

Config.Mods.WindowTints = {
  { modIndex = 0, name = "Brak przyciemnienia" },
  { modIndex = 3, name = "Jasny dym" },
  { modIndex = 2, name = "Ciemny dym" },
  { modIndex = 1, name = "Czysta czerń" }
}

Config.Mods.WheelTypes = {
  { modIndex = 0, name = "Sportowe" },
  { modIndex = 1, name = "Muscle" },
  { modIndex = 2, name = "Lowrider" },
  { modIndex = 3, name = "SUV" },
  { modIndex = 4, name = "Offroad" },
  { modIndex = 5, name = "Tuningowe" },
  { modIndex = 6, name = "Motocyklowe" },
  { modIndex = 7, name = "Premium" },
  { modIndex = 8, name = "Oryginalne Benny'ego" },
  { modIndex = 9, name = "Indywidualne Benny'ego" },
  { modIndex = 10, name = "Open Wheel" },
  { modIndex = 11, name = "Uliczne" },
  { modIndex = 12, name = "Wyścigowe" },
}

Config.Mods.Horns = {
  { modIndex = -1, name = "Standardowy", musical = false },
  { modIndex = 0,  name = "Klakson ciężarówki", musical = false },
  { modIndex = 1,  name = "Klakson policyjny", musical = false },
  { modIndex = 2,  name = "Klakson klauna", musical = false },
  { modIndex = 3,  name = "Klakson muzyczny 1", musical = true },
  { modIndex = 4,  name = "Klakson muzyczny 2", musical = true },
  { modIndex = 5,  name = "Klakson muzyczny 3", musical = true },
  { modIndex = 6,  name = "Klakson muzyczny 4", musical = true },
  { modIndex = 7,  name = "Klakson muzyczny 5", musical = true },
  { modIndex = 8,  name = "Smutny puzon", musical = true },
  { modIndex = 9,  name = "Klakson klasyczny 1", musical = true },
  { modIndex = 10, name = "Klakson klasyczny 2", musical = true },
  { modIndex = 11, name = "Klakson klasyczny 3", musical = true },
  { modIndex = 12, name = "Klakson klasyczny 4", musical = true },
  { modIndex = 13, name = "Klakson klasyczny 5", musical = true },
  { modIndex = 14, name = "Klakson klasyczny 6", musical = true },
  { modIndex = 15, name = "Klakson klasyczny 7", musical = true },
  { modIndex = 16, name = "Skala - Do", musical = false },
  { modIndex = 17, name = "Skala - Re", musical = false },
  { modIndex = 18, name = "Skala - Mi", musical = false },
  { modIndex = 19, name = "Skala - Fa", musical = false },
  { modIndex = 20, name = "Skala - Sol", musical = false },
  { modIndex = 21, name = "Skala - La", musical = false },
  { modIndex = 22, name = "Skala - Ti", musical = false },
  { modIndex = 23, name = "Skala - Do", musical = false },
  { modIndex = 24, name = "Klakson jazzowy 1", musical = true },
  { modIndex = 25, name = "Klakson jazzowy 2", musical = true },
  { modIndex = 26, name = "Klakson jazzowy 3", musical = true },
  { modIndex = 27, name = "Klakson jazzowy (loop)", musical = true },
  { modIndex = 28, name = "Hymn USA 1", musical = true },
  { modIndex = 29, name = "Hymn USA 2", musical = true },
  { modIndex = 30, name = "Hymn USA 3", musical = true },
  { modIndex = 31, name = "Hymn USA 4", musical = true },
  { modIndex = 32, name = "Klakson klasyczny 8 (loop)", musical = true },
  { modIndex = 33, name = "Klakson klasyczny 9 (loop)", musical = true },
  { modIndex = 34, name = "Klakson klasyczny 10 (loop)", musical = true },
  { modIndex = 35, name = "Klakson klasyczny 8", musical = true },
  { modIndex = 36, name = "Klakson klasyczny 9", musical = true },
  { modIndex = 37, name = "Klakson klasyczny 10", musical = true },
  { modIndex = 38, name = "Marsz żałobny (loop)", musical = true },
  { modIndex = 39, name = "Marsz żałobny", musical = true },
  { modIndex = 40, name = "Upiorny (loop)", musical = true },
  { modIndex = 41, name = "Upiorny", musical = true },
  { modIndex = 42, name = "San Andreas (loop)", musical = true },
  { modIndex = 43, name = "San Andreas", musical = true },
  { modIndex = 44, name = "Liberty City (loop)", musical = true },
  { modIndex = 45, name = "Liberty City", musical = true },
  { modIndex = 46, name = "Świąteczny 1 (loop)", musical = true },
  { modIndex = 47, name = "Świąteczny 1", musical = true },
  { modIndex = 48, name = "Świąteczny 2 (loop)", musical = true },
  { modIndex = 49, name = "Świąteczny 2", musical = true },
  { modIndex = 50, name = "Świąteczny 3 (loop)", musical = true },
  { modIndex = 51, name = "Świąteczny 3", musical = true },
  { modIndex = 52, name = "Klakson powietrzny niski (loop)", musical = false },
  { modIndex = 53, name = "Klakson powietrzny niski", musical = false },
  { modIndex = 54, name = "Klakson powietrzny średni (loop)", musical = false },
  { modIndex = 55, name = "Klakson powietrzny średni", musical = false },
  { modIndex = 56, name = "Klakson powietrzny wysoki (loop)", musical = false },
  { modIndex = 57, name = "Klakson powietrzny wysoki", musical = false },
}

Config.Mods.Colours = {
  { name = "Podstawowy", paintTypeKey = "paintType1", colourKey = "color1" },
  { name = "Dodatkowy", paintTypeKey = "paintType2", colourKey = "color2" },
  { name = "Perłowy", colourIdKey = "pearlescentColor" },
  { name = "Deska rozdzielcza", colourIdKey = "dashboardColor" },
  { name = "Wnętrze", colourIdKey = "interiorColor" },
  { name = "Koła", colourIdKey = "wheelColor" },
}

-- Można zmienić nazwy ale NIE kolejność
Config.Mods.RgbPaintFinishes = {
  "Standardowy",
  "Metalik",
  "Perłowy",
  "Matowy",
  "Metal",
  "Chrom"
}

Config.Mods.GtaColours = {
  Metallic = {
    { modIndex = 0, name = "Czarny",                    hex = "0d1116" },
    { modIndex = 1, name = "Czarny Grafitowy",           hex = "1c1d21" },
    { modIndex = 2, name = "Czarna Stal",              hex = "32383d" },
    { modIndex = 3, name = "Ciemny Srebrny",              hex = "454b4f" },
    { modIndex = 4, name = "Srebrny",                   hex = "999da0" },
    { modIndex = 5, name = "Niebiesko-Srebrny",              hex = "c2c4c6" },
    { modIndex = 6, name = "Szarość Stalowa",               hex = "979a97" },
    { modIndex = 7, name = "Srebrny Cień",            hex = "637380" },
    { modIndex = 8, name = "Srebrny Kamień",             hex = "63625c" },
    { modIndex = 9, name = "Północny Srebrny",          hex = "3c3f47" },
    { modIndex = 10, name = "Gun Metal",               hex = "444e54" },
    { modIndex = 11, name = "Antracytowa Szarość",         hex = "1d2129" },
    { modIndex = 27, name = "Czerwony",                     hex = "c00e1a" },
    { modIndex = 28, name = "Czerwony Torino",              hex = "da1918" },
    { modIndex = 29, name = "Czerwony Formuła",             hex = "b6111b" },
    { modIndex = 30, name = "Płomienna Czerwień",               hex = "a51e23" },
    { modIndex = 31, name = "Wytworna Czerwień",            hex = "7b1a22" },
    { modIndex = 32, name = "Czerwony Granat",              hex = "8e1b1f" },
    { modIndex = 33, name = "Pustynna Czerwień",              hex = "6f1818" },
    { modIndex = 34, name = "Czerwony Cabernet",            hex = "49111d" },
    { modIndex = 35, name = "Czerwony Cukierkowy",               hex = "b60f25" },
    { modIndex = 36, name = "Pomarańcza Wschodu Słońca",          hex = "d44a17" },
    { modIndex = 37, name = "Klasyczne Złoto",            hex = "c2944f" },
    { modIndex = 38, name = "Pomarańczowy",                  hex = "f78616" },
    { modIndex = 49, name = "Ciemna Zieleń",              hex = "132428" },
    { modIndex = 50, name = "Zieleń Wyścigowa",            hex = "122e2b" },
    { modIndex = 51, name = "Morska Zieleń",               hex = "12383c" },
    { modIndex = 52, name = "Oliwkowa Zieleń",             hex = "31423f" },
    { modIndex = 53, name = "Zielony",                   hex = "155c2d" },
    { modIndex = 54, name = "Niebiesko-Zielony Benzyna",     hex = "1b6770" },
    { modIndex = 61, name = "Północny Błękit",           hex = "222e46" },
    { modIndex = 62, name = "Ciemny Niebieski",               hex = "233155" },
    { modIndex = 63, name = "Błękit Saksoński",             hex = "304c7e" },
    { modIndex = 64, name = "Niebieski",                    hex = "47578f" },
    { modIndex = 65, name = "Błękit Marynarski",            hex = "637ba7" },
    { modIndex = 66, name = "Błękit Portowy",             hex = "394762" },
    { modIndex = 67, name = "Diamentowy Błękit",            hex = "d6e7f1" },
    { modIndex = 68, name = "Błękit Surfowania",               hex = "76afbe" },
    { modIndex = 69, name = "Morski Błękit",           hex = "345e72" },
    { modIndex = 70, name = "Jaskrawy Błękit",             hex = "0b9cf1" },
    { modIndex = 71, name = "Fioletowo-Niebieski",             hex = "2f2d52" },
    { modIndex = 72, name = "Błękit Żaglowy",          hex = "282c4d" },
    { modIndex = 73, name = "Ultra Błękit",              hex = "2354a1" },
    { modIndex = 74, name = "Jaskrawy Błękit",             hex = "6ea3c6" },
    { modIndex = 88, name = "Żółty Taxiówki",             hex = "ffcf20" },
    { modIndex = 89, name = "Żółty Wyścigowy",             hex = "fbe212" },
    { modIndex = 90, name = "Brązowy",                  hex = "916532" },
    { modIndex = 91, name = "Żółty Ptak",             hex = "e0e13d" },
    { modIndex = 92, name = "Limonkowy",                    hex = "98d223" },
    { modIndex = 93, name = "Szampan",               hex = "9b8c78" },
    { modIndex = 94, name = "Beż Pueblo",            hex = "503218" },
    { modIndex = 95, name = "Ciemna Kość Słoniowa",              hex = "473f2b" },
    { modIndex = 96, name = "Czekoladowy Brąz",             hex = "221b19" },
    { modIndex = 97, name = "Złocisty Brąz",            hex = "653f23" },
    { modIndex = 98, name = "Jasny Brąz",             hex = "775c3e" },
    { modIndex = 99, name = "Słomkowy Beż",             hex = "ac9975" },
    { modIndex = 100, name = "Brązowy Mech",             hex = "6c6b4b" },
    { modIndex = 101, name = "Brąz Biston",           hex = "402e2b" },
    { modIndex = 102, name = "Bukowe Drewno",              hex = "a4965f" },
    { modIndex = 103, name = "Ciemne Bukowe Drewno",         hex = "46231a" },
    { modIndex = 104, name = "Czekoladowa Pomarańcza",           hex = "752b19" },
    { modIndex = 105, name = "Piasek Plaży",             hex = "bfae7b" },
    { modIndex = 106, name = "Wyblakły Piasek",      hex = "dfd5b2" },
    { modIndex = 107, name = "Kremowy",                  hex = "f7edd5" },
    { modIndex = 111, name = "Biały",                  hex = "fffff6" },
    { modIndex = 112, name = "Mroźna Biel",            hex = "eaeaea" },
    { modIndex = 125, name = "Zieleń Securicor",        hex = "83c566" },
    { modIndex = 137, name = "Róż Vermillion",        hex = "df5891" },
    { modIndex = 141, name = "Czarno-Niebieski",             hex = "0a0c17" },
    { modIndex = 142, name = "Czarno-Fioletowy",           hex = "0c0d18" },
    { modIndex = 143, name = "Czarno-Czerwony",              hex = "0e0d14" },
    { modIndex = 145, name = "Fioletowy",                 hex = "621276" },
    { modIndex = 146, name = "Bardzo Ciemny Niebieski",            hex = "0b1421" },
    { modIndex = 150, name = "Czerwień Lawy",               hex = "bc1917" },
  },
  Matte = {
    { modIndex = 12, name = "Czarny",                   hex = "13181f" },
    { modIndex = 13, name = "Szary",                    hex = "26282a" },
    { modIndex = 14, name = "Jasny Szary",              hex = "515554" },
    { modIndex = 39, name = "Czerwony",                     hex = "cf1f21" },
    { modIndex = 40, name = "Ciemna Czerwień",                hex = "732021" },
    { modIndex = 41, name = "Pomarańczowy",                  hex = "f27d20" },
    { modIndex = 42, name = "Żółty",                  hex = "ffc91f" },
    { modIndex = 55, name = "Limonkowa Zieleń",              hex = "66b81f" },
    { modIndex = 82, name = "Ciemny Niebieski",               hex = "1f2852" },
    { modIndex = 83, name = "Niebieski",                    hex = "253aa7" },
    { modIndex = 84, name = "Północny Błękit",           hex = "1c3551" },
    { modIndex = 128, name = "Zielony",                  hex = "4e6443" },
    { modIndex = 129, name = "Brązowy",                  hex = "bcac8f" },
    { modIndex = 131, name = "Biały",                  hex = "fcf9f1" },
    { modIndex = 148, name = "Fioletowy",                 hex = "6b1f7b" },
    { modIndex = 149, name = "Ciemny Fiolet",            hex = "1e1d22" },
    { modIndex = 151, name = "Leśna Zieleń",           hex = "2d362a" },
    { modIndex = 152, name = "Oliwkowa Zieleń Maskująca",             hex = "696748" },
    { modIndex = 153, name = "Pustynny Brąz",           hex = "7a6c55" },
    { modIndex = 154, name = "Pustynny Beż",             hex = "c3b492" },
    { modIndex = 155, name = "Zieleń Liściasta",          hex = "5a6352" },
  },
  Util = {
    { modIndex = 15, name = "Czarny",                   hex = "151921" },
    { modIndex = 16, name = "Czarny Poli",              hex = "1e2429" },
    { modIndex = 17, name = "Ciemny Srebrny",             hex = "333a3c" },
    { modIndex = 18, name = "Srebrny",                  hex = "8c9095" },
    { modIndex = 19, name = "Gun Metal",               hex = "39434d" },
    { modIndex = 20, name = "Srebrny Cień",           hex = "506272" },
    { modIndex = 43, name = "Czerwony",                     hex = "9c1016" },
    { modIndex = 44, name = "Jaskrawa Czerwień",              hex = "de0f18" },
    { modIndex = 45, name = "Czerwony Granat",              hex = "8f1e17" },
    { modIndex = 56, name = "Ciemna Zieleń",              hex = "22383e" },
    { modIndex = 57, name = "Zielony",                   hex = "1d5a3f" },
    { modIndex = 75, name = "Ciemny Niebieski",               hex = "112552" },
    { modIndex = 76, name = "Północny Błękit",           hex = "1b203e" },
    { modIndex = 77, name = "Niebieski",                    hex = "275190" },
    { modIndex = 78, name = "Błękit Morskiej Piany",           hex = "608592" },
    { modIndex = 79, name = "Błękit Błyskawicy",          hex = "2446a8" },
    { modIndex = 80, name = "Błękit Maui Poli",          hex = "4271e1" },
    { modIndex = 81, name = "Jaskrawy Błękit",             hex = "3b39e0" },
    { modIndex = 108, name = "Brązowy",                  hex = "3a2a1b" },
    { modIndex = 109, name = "Średni Brąz",           hex = "785f33" },
    { modIndex = 110, name = "Jasny Brąz",            hex = "b5a079" },
    { modIndex = 122, name = "Kremowa Biel",              hex = "dfddd0" },
  },      
  Worn = {      
    { modIndex = 21, name = "Czarny",                   hex = "1e232f" },
    { modIndex = 22, name = "Grafitowy",                hex = "363a3f" },
    { modIndex = 23, name = "Srebrna Szarość",             hex = "a0a199" },
    { modIndex = 24, name = "Srebrny",                  hex = "d3d3d3" },
    { modIndex = 25, name = "Niebiesko-Srebrny",             hex = "b7bfca" },
    { modIndex = 26, name = "Srebrny Cień",           hex = "778794" },
    { modIndex = 46, name = "Czerwony",                     hex = "a94744" },
    { modIndex = 47, name = "Złocista Czerwień",              hex = "b16c51" },
    { modIndex = 48, name = "Ciemna Czerwień",                hex = "371c25" },
    { modIndex = 58, name = "Ciemna Zieleń",              hex = "2d423f" },
    { modIndex = 59, name = "Zielony",                   hex = "45594b" },
    { modIndex = 60, name = "Morska Piana",                hex = "65867f" },
    { modIndex = 85, name = "Ciemny Niebieski",               hex = "4c5f81" },
    { modIndex = 86, name = "Niebieski",                    hex = "58688e" },
    { modIndex = 87, name = "Jasny Niebieski",              hex = "74b5d8" },
    { modIndex = 113, name = "Miodowy Beż",            hex = "b0ab94" },
    { modIndex = 114, name = "Brązowy",                  hex = "453831" },
    { modIndex = 115, name = "Ciemny Brąz",             hex = "2a282b" },
    { modIndex = 116, name = "Słomkowy Beż",            hex = "726c57" },
    { modIndex = 121, name = "Kremowa Biel",              hex = "eae6de" },
    { modIndex = 123, name = "Pomarańczowy",                 hex = "f2ad2e" },
    { modIndex = 124, name = "Jasna Pomarańcza",           hex = "f9a458" },
    { modIndex = 126, name = "Żółty Taxiówki",            hex = "f1cc40" },
    { modIndex = 130, name = "Pomarańczowy",                 hex = "f8b658" },
    { modIndex = 132, name = "Biały",                  hex = "fffffb" },
    { modIndex = 133, name = "Oliwkowa Zieleń Wojskowa",       hex = "81844c" },
  },
  Misc = {
    { modIndex = 117, name = "Szczotkowana Stal",          hex = "6a747c" },
    { modIndex = 118, name = "Szczotkowana Czarna Stal",    hex = "354158" },
    { modIndex = 119, name = "Szczotkowane Aluminium",      hex = "9ba0a8" },
    { modIndex = 120, name = "Chrom",                 hex = "5870a1" },
    { modIndex = 127, name = "Niebieski Policyjny",        hex = "4cc3da" },
    { modIndex = 134, name = "Czysta Biel",             hex = "ffffff" },
    { modIndex = 135, name = "Jaskrawy Róż",               hex = "f21f99" },
    { modIndex = 136, name = "Róż Łososiowy",            hex = "fdd6cd" },
    { modIndex = 138, name = "Pomarańczowy",                 hex = "f6ae20" },
    { modIndex = 139, name = "Zielony",                  hex = "b0ee6e" },
    { modIndex = 140, name = "Niebieski",                   hex = "08e9fa" },
    { modIndex = 144, name = "Myśliwska Zieleń",           hex = "9f9e8a" },
    { modIndex = 147, name = "Czarny z Warsztatu",         hex = "11141a" },
    { modIndex = 156, name = "Stop",                  hex = "81827f" },
    { modIndex = 157, name = "Błękit Epsilon",           hex = "afd6e4" },
    { modIndex = 158, name = "Czyste Złoto",              hex = "7a6440" },
    { modIndex = 159, name = "Szczotkowane Złoto",           hex = "7f6a48" }
  },
  Chameleon = {
    { modIndex = 161, name = "Anodowana Czerwień",           hex = "CF1020" },
    { modIndex = 162, name = "Anodowane Wino",          hex = "5E1224" },
    { modIndex = 163, name = "Anodowany Fiolet",        hex = "800080" },
    { modIndex = 164, name = "Anodowany Niebieski",          hex = "0000FF" },
    { modIndex = 165, name = "Anodowana Zieleń",         hex = "008000" },
    { modIndex = 166, name = "Anodowana Limonka",          hex = "AFFF00" },
    { modIndex = 167, name = "Anodowana Miedź",        hex = "B87333" },
    { modIndex = 168, name = "Anodowany Brąz",        hex = "CD7F32" },
    { modIndex = 169, name = "Anodowany Szampan",     hex = "F7E7CE" },
    { modIndex = 170, name = "Anodowane Złoto",          hex = "FFD700" },
    { modIndex = 171, name = "Zielono-Niebieski Flip",        hex = "1164B4" },
    { modIndex = 172, name = "Zielono-Czerwony Flip",         hex = "B43104" },
    { modIndex = 173, name = "Zielono-Brązowy Flip",       hex = "735C12" },
    { modIndex = 174, name = "Zielono-Turkusowy Flip",   hex = "43C6DB" },
    { modIndex = 175, name = "Zielono-Fioletowy Flip",      hex = "9D00FF" },
    { modIndex = 176, name = "Turkusowo-Fioletowy Flip",       hex = "6A0DAD" },
    { modIndex = 177, name = "Turkusowo-Czerwony Flip",     hex = "E60026" },
    { modIndex = 178, name = "Turkusowo-Fioletowy Flip",  hex = "30D5C8" },
    { modIndex = 179, name = "Cyjanowo-Fioletowy Flip",       hex = "0FF0FC" },
    { modIndex = 180, name = "Niebiesko-Różowy Flip",         hex = "4C2882" },
    { modIndex = 181, name = "Niebiesko-Zielony Flip",        hex = "138808" },
    { modIndex = 182, name = "Fioletowo-Czerwony Flip",        hex = "9B111E" },
    { modIndex = 183, name = "Fioletowo-Zielony Flip",      hex = "6B2E53" },
    { modIndex = 184, name = "Magenta-Zielony Flip",     hex = "CA1F7B" },
    { modIndex = 185, name = "Magenta-Żółty Flip",    hex = "FEDF00" },
    { modIndex = 186, name = "Bordowo-Zielony Flip",    hex = "900020" },
    { modIndex = 187, name = "Magenta-Cyjan Flip",      hex = "00FFA1" },
    { modIndex = 188, name = "Miedziano-Fioletowy Flip",     hex = "B87333" },
    { modIndex = 189, name = "Magenta-Pomarańczowy Flip",    hex = "FF5F1F" },
    { modIndex = 190, name = "Czerwono-Pomarańczowy Flip",        hex = "FF4500" },
    { modIndex = 191, name = "Pomarańczowo-Fioletowy Flip",     hex = "B04080" },
    { modIndex = 192, name = "Pomarańczowo-Niebieski Flip",       hex = "0047AB" },
    { modIndex = 193, name = "Biało-Fioletowy Flip",      hex = "F8F0E3" },
    { modIndex = 194, name = "Czerwona Tęcza Flip",       hex = "ED2939" },
    { modIndex = 195, name = "Niebieska Tęcza Flip",      hex = "4B0082" },
    { modIndex = 196, name = "Ciemna Zieleń Perłowa",       hex = "013220" },
    { modIndex = 197, name = "Ciemny Turkus Perłowy",        hex = "008080" },
    { modIndex = 198, name = "Ciemny Niebieski Perłowy",        hex = "000080" },
    { modIndex = 199, name = "Ciemny Fiolet Perłowy",      hex = "301934" },
    { modIndex = 200, name = "Perłowy Olejowy",        hex = "4B0082" },
    { modIndex = 201, name = "Jasna Zieleń Perłowa",      hex = "99E550" },
    { modIndex = 202, name = "Jasny Niebieski Perłowy",       hex = "ADD8E6" },
    { modIndex = 203, name = "Jasny Róż Perłowy",       hex = "FFB6C1" },
    { modIndex = 204, name = "Kremowa Biel Perłowa",        hex = "F2F0E6" },
    { modIndex = 205, name = "Róż Perłowy",             hex = "EAADEA" },
    { modIndex = 206, name = "Żółty Perłowy",           hex = "FFF000" },
    { modIndex = 207, name = "Zielony Perłowy",            hex = "00A550" },
    { modIndex = 208, name = "Niebieski Perłowy",             hex = "0000FF" },
    { modIndex = 209, name = "Krem Perłowy",            hex = "FFFDD0" },
    { modIndex = 210, name = "Biały Pryzmatyczny",        hex = "FFFFFF" },
    { modIndex = 211, name = "Grafit Pryzmatyczny",     hex = "251607" },
    { modIndex = 212, name = "Ciemny Niebieski Pryzmatyczny",    hex = "00008B" },
    { modIndex = 213, name = "Ciemny Fiolet Pryzmatyczny",  hex = "301934" },
    { modIndex = 214, name = "Jaskrawy Róż Pryzmatyczny",     hex = "FF69B4" },
    { modIndex = 215, name = "Ciemna Czerwień Pryzmatyczna",     hex = "8B0000" },
    { modIndex = 216, name = "Ciemna Zieleń Pryzmatyczna",   hex = "013220" },
    { modIndex = 217, name = "Czarny Pryzmatyczny",        hex = "000000" },
    { modIndex = 218, name = "Czarny Wyciek Oleju",        hex = "121212" },
    { modIndex = 219, name = "Czarna Tęcza",          hex = "000000" },
    { modIndex = 220, name = "Pryzmatyczny",              hex = "CCCCCC" },
    { modIndex = 221, name = "Czarny Holograficzny",      hex = "101010" },
    { modIndex = 222, name = "Biały Holograficzny",      hex = "E6E8FA" },
    { modIndex = 223, name = "Monochromatyczny",             hex = "B4B4B4" },
    { modIndex = 224, name = "Noc i Dzień",            hex = "333366" },
    { modIndex = 225, name = "The Verlierer",          hex = "550055" },
    { modIndex = 226, name = "Sprunk Extreme",         hex = "00FF00" },
    { modIndex = 227, name = "Vice City",              hex = "FF00FF" },
    { modIndex = 228, name = "Synthwave Nights",       hex = "FF007F" },
    { modIndex = 229, name = "Cztery Pory Roku",           hex = "73C2FB" },
    { modIndex = 230, name = "Maisonette 9 Retro", hex = "DCDCDC" },
    { modIndex = 231, name = "Guma Balonowa",              hex = "FFC0CB" },
    { modIndex = 232, name = "Pełna Tęcza",           hex = "FF0000" },
    { modIndex = 233, name = "Zachód Słońca",                 hex = "FFD700" },
    { modIndex = 234, name = "The Seven",              hex = "701C1C" },
    { modIndex = 235, name = "Kamen Rider",            hex = "1C1C70" },
    { modIndex = 236, name = "Aberracja Chromowa",   hex = "D8BFD8" },
    { modIndex = 237, name = "Święta",         hex = "FF0000" },
    { modIndex = 238, name = "Temperatura",            hex = "FFA07A" },
    { modIndex = 239, name = "Żółto-Pomarańczowy Perłowy",    hex = "FFAE42" },
    { modIndex = 240, name = "Różowo-Niebieski Perłowy",        hex = "D8BFD8" },
    { modIndex = 241, name = "Zielono-Niebieski Perłowy",       hex = "3CB371" },
    { modIndex = 242, name = "Turkusowo-Czarny Perłowy",  hex = "00CED1" }
  }
}

Config.Mods.XenonColours = {
  { modIndex = 0,  name = "Biały",          hex = "DEDEFF" },
  { modIndex = 1,  name = "Niebieski",           hex = "0215FF" },
  { modIndex = 2,  name = "Elektryczny Błękit",  hex = "0353FF" },
  { modIndex = 3,  name = "Miętowa Zieleń",     hex = "00FF8C" },
  { modIndex = 4,  name = "Limonkowa Zieleń",     hex = "5EFF01" },
  { modIndex = 5,  name = "Żółty",         hex = "FFFF00" },
  { modIndex = 6,  name = "Złoty Deszcz",  hex = "FF9600" },
  { modIndex = 7,  name = "Pomarańczowy",         hex = "FF3E00" },
  { modIndex = 8,  name = "Czerwony",            hex = "FF0101" },
  { modIndex = 9,  name = "Róż Kucyka",      hex = "FF3264" },
  { modIndex = 10, name = "Jaskrawy Róż",       hex = "FF05BE" },
  { modIndex = 11, name = "Fioletowy",         hex = "2301FF" },
  { modIndex = 12, name = "Czarne Światło",     hex = "0F03FF" }
}